Repository kubesphere/ks-installer, pull requests merged in 2020-11, with the labels that each got.

#1153 feature: add owners for prow
  OWNERS
Labels: dco-signoff: yes, size/S

#1155 update get nodes method
  controller/installRunner.py
Labels: dco-signoff: yes

#1154 add group crds
  roles/common/files/ks-crds/iam.kubesphere.io_groupbindings.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_groups.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1152 Add metering rules
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, lgtm

#1148 Remove jenkins update center component
  roles/download/defaults/main.yml
  roles/ks-devops/jenkins-update-center/defaults/main.yaml
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/.helmignore
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/Chart.yaml
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/NOTES.txt
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/_helpers.tpl
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/deployment.yaml
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/ingress.yaml
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/service.yaml
  roles/ks-devops/jenkins-update-center/tasks/main.yaml
  roles/ks-devops/jenkins-update-center/templates/values-jenkins-uc.yaml.j2
  roles/ks-devops/jenkins/files/jenkins/jenkins/README.md
  roles/ks-devops/jenkins/files/jenkins/jenkins/templates/_helpers.tpl
  roles/ks-devops/jenkins/files/jenkins/jenkins/templates/config.yaml
  roles/ks-devops/jenkins/files/jenkins/jenkins/templates/jenkins-master-deployment.yaml
  roles/ks-devops/jenkins/files/jenkins/jenkins/values.yaml
  roles/ks-devops/jenkins/templates/custom-values-jenkins.yaml.j2
  roles/ks-devops/meta/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1156 update the yaml url of v2.1.1 in readme
  README.md
  README_zh.md
Labels: dco-signoff: yes, lgtm, size/XS

#1158 helm list add flags -f to resolve helm list error
  roles/metrics-server/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1159 Fix the missing end statemnet of Jenkins chart
  roles/download/defaults/main.yml
  roles/ks-devops/jenkins/files/jenkins/jenkins/templates/config.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1161 Fix servicemonitor label selector
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1163 Set the default value of Jenkins HealthProbes as true
  roles/ks-devops/jenkins/templates/custom-values-jenkins.yaml.j2
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/XS

#1164 Add monitoring endpoint option
  deploy/cluster-configuration.yaml
  docs/vars.md
  roles/common/defaults/main.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1166 if snapshot controller exist, ignore deploy failed
  roles/common/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1167 update README
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, size/XS

#1168 support install kiali
  deploy/kubesphere-installer.yaml
  roles/download/defaults/main.yml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-istio/files/istio/jaeger-operator/.helmignore
  roles/ks-istio/files/istio/jaeger-operator/Chart.yaml
  roles/ks-istio/files/istio/jaeger-operator/OWNERS
  roles/ks-istio/files/istio/jaeger-operator/README.md
  roles/ks-istio/files/istio/jaeger-operator/crds/crd.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/NOTES.txt
  roles/ks-istio/files/istio/jaeger-operator/templates/_helpers.tpl
  roles/ks-istio/files/istio/jaeger-operator/templates/crds.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/deployment.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/jaeger.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/psp.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/role-binding.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/role.yaml
  roles/ks-istio/files/istio/jaeger-operator/templates/service-account.yaml
  roles/ks-istio/files/jaeger/custom-values-jaeger.yaml
  roles/ks-istio/files/jaeger/jaeger-operator-2.14.2.tgz
  roles/ks-istio/files/jaeger/jaeger-operator-service.yaml
  roles/ks-istio/files/jaeger/jaeger-production.yaml
  roles/ks-istio/files/kiali/custom-values-kiali.yaml
  roles/ks-istio/files/kiali/kiali-server-1.26.1.tgz
  roles/ks-istio/tasks/jaeger-install.yaml
  roles/ks-istio/tasks/kiali-install.yaml
  roles/ks-istio/tasks/main.yaml
  roles/ks-istio/tasks/upgrade-pre.yaml
  roles/ks-istio/templates/custom-values-kiali.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1165 Add rule namespace:meter_pvc_bytes_total:sum
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1169 modify kiali repo && grant privileges
  roles/download/defaults/main.yml
  roles/ks-istio/files/istio/clusterroles.yaml
  roles/ks-istio/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1172 kiali change quay.io to kubespheredev repo
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: no, lgtm, size/XS

#1171 fix: error image name
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1170 feature: add s2i webhook
  roles/download/defaults/main.yml
  roles/ks-devops/s2i/templates/s2ioperator.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1173 fix: s2i deploy failed
  roles/ks-devops/s2i/tasks/main.yaml
  roles/ks-devops/s2i/templates/s2ioperator.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/L
