Repository kubesphere/ks-installer, pull requests merged in 2020-12, with the labels that each got.

#1176 update jenkins-uc chart
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/deployment.yaml
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/nginx-conf.yaml
Labels: dco-signoff: yes, lgtm, size/M

#1175 feature: Auto test
  .github/workflows/auto-test.yml
  .github/workflows/deploy/install.sh
  .github/workflows/deploy/kubesphere.tf
  .github/workflows/deploy/var.tf
Labels: dco-signoff: yes, size/L

#1177 support etcd multi arch
  playbooks/common.yaml
  roles/common/templates/etcd.yaml.j2
Labels: dco-signoff: yes, size/XS

#1178 support etcd multi arch
  roles/common/templates/etcd.yaml.j2
Labels: dco-signoff: no, size/XS

#1179 fix format
  roles/common/templates/etcd.yaml.j2
Labels: dco-signoff: yes, size/XS

#1180 fix nginx conf
  roles/ks-devops/jenkins-update-center/files/jenkins-update-center/templates/deployment.yaml
Labels: dco-signoff: yes, size/XS

#1181 fix: modify check script
  .github/workflows/auto-test.yml
  .github/workflows/deploy/install.sh
Labels: dco-signoff: yes, size/S

#1182 custom container log path
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
Labels: dco-signoff: yes, size/XS

#1183 update container log path parameter
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
Labels: dco-signoff: yes, size/XS

#1184 conatiner log mount path
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
Labels: dco-signoff: yes, size/XS

#1174 Fix the missing part of ks-jenkins configmap
  roles/ks-devops/jenkins/files/jenkins/jenkins/templates/config.yaml
  scripts/images-list.txt
Labels: approved, area/devops, dco-signoff: yes, do-not-merge/hold, lgtm, size/XS

#1186 feature: switch test latest
  .github/workflows/auto-test.yml
  .github/workflows/deploy/install.sh
Labels: dco-signoff: yes, size/M

#1187 fix: error kubectl images
  roles/download/defaults/main.yml
Labels: dco-signoff: no, size/XS

#1189 fix: add more components to autotest
  .github/workflows/auto-test.yml
  .github/workflows/deploy/install.sh
  .github/workflows/deploy/kubesphere.tf
Labels: dco-signoff: no, size/S

#1191 fix galley check
  roles/ks-istio/tasks/kiali-install.yaml
  roles/ks-istio/tasks/upgrade-pre.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1190 update initial account
  roles/common/files/ks-crds/iam.kubesphere.io_users.yaml
  roles/ks-core/prepare/files/ks-init/admin.yaml
  roles/ks-core/prepare/files/ks-init/initial-account.yaml
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
  roles/ks-core/prepare/tasks/ks-init.yaml
  roles/ks-core/prepare/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1193 refine the command line
  .github/workflows/deploy/install.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1195 Add federated group crd
  roles/ks-multicluster/files/kubefed/federatedcrds/groupbindings.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/groups.iam.kubesphere.io.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1194 update servicemesh image
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#1196 update istio prometheus config
  roles/ks-istio/files/prometheus/additional-scrape-configs.yaml
  roles/ks-istio/files/prometheus/prometheus-additional.yaml
  roles/ks-istio/files/prometheus/readme.md
  roles/ks-istio/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1197 Add rule namespace:pvc_bytes_pod:sum
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1199 remove jaeger-operator service
  roles/ks-istio/files/istio/readme.md
  roles/ks-istio/files/jaeger/jaeger-operator-service.yaml
  roles/ks-istio/files/jaeger/jaeger-production.yaml
  roles/ks-istio/files/jaeger/readme.md
  roles/ks-istio/files/kiali/readme.md
  roles/ks-istio/files/prometheus/readme.md
  roles/ks-istio/tasks/jaeger-install.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1201 support aliyun image repo
  roles/download/defaults/main.yml
  roles/ks-monitor/tasks/generate_manifests.yaml
  roles/kubesphere-defaults/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1204 support install ingressGateways
  deploy/cluster-configuration.yaml
  roles/download/defaults/main.yml
  roles/ks-istio/templates/istio-profile.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1207 Rename namespace:pvc_bytes_pod:sum to namespace:pvc_bytes_total:sum
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1206 update audit images
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1205 add nginx ingress prometheus config
  roles/ks-istio/files/prometheus/additional-scrape-configs.yaml
  roles/ks-istio/files/prometheus/prometheus-additional.yaml
  roles/ks-istio/files/prometheus/readme.md
  roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1209 update auditing version
  roles/ks-auditing/files/kube-auditing/Chart.yaml
  roles/ks-auditing/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1202 Add Jenkins upgrade guide
  docs/JenkinsUpgradeGuide.md
  roles/download/defaults/main.yml
  roles/ks-devops/jenkins/templates/jenkins-casc-config.yml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1211 Remove steal mode from cpu used calculation
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1212 update minio make bucket label
  roles/common/files/minio-ha/templates/post-install-create-bucket-job.yaml
Labels: approved, dco-signoff: yes, size/XS

#1210 Add a GitHub action for nightly build
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1213 update nightly build policy
  .github/workflows/nightly-builds.yml
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, size/S

#1214 feature: deploy weekly
  .github/workflows/deploy-test.yml
  .github/workflows/deploy-weekly.yml
  .github/workflows/deploy-weekly/install.sh
  .github/workflows/deploy-weekly/kubesphere.tf
  .github/workflows/deploy-weekly/var.tf
Labels: dco-signoff: no

#1215 improvement: rename files and webhook name
  .github/workflows/deploy-test.yml
  .github/workflows/deploy-test/install.sh
  .github/workflows/deploy-test/kubesphere.tf
  .github/workflows/deploy-test/var.tf
  .github/workflows/deploy-weekly.yml
  .github/workflows/nightly-builds.yml
Labels: dco-signoff: yes, size/S

#1216 improvement: rename webhook
  .github/workflows/deploy-test.yml
  .github/workflows/deploy-weekly.yml
Labels: dco-signoff: yes, size/XS

#1219 Uses kubectl apply to create or update crds
  roles/common/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1217 Fix the wrong indent of gitLabServers
  roles/ks-devops/jenkins/templates/jenkins-casc-config.yml.j2
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/XS
