Repository kubesphere/ks-installer, pull requests merged in 2021-06, with the labels that each got.

#1490 Add service monitor for jenkins
  docs/JenkinsUpgradeGuide.md
  roles/common/tasks/init-namespaces.yaml
  roles/ks-devops/jenkins/defaults/main.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-devops/jenkins/templates/jenkins-casc-config.yml.j2
  roles/ks-devops/jenkins/templates/worker-resourcequota.yaml.j2
  roles/ks-monitor/files/prometheus/devops/prometheus-jenkinsAlertRules.yaml
  roles/ks-monitor/files/prometheus/devops/prometheus-serviceMonitorJenkins.yaml
  scripts/kubesphere-delete.sh
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/L

#1528 support external prometheus stack
  deploy/cluster-configuration.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/prometheus-stack.yaml
Labels: dco-signoff: yes, kind/feature, lgtm, size/M

#1533 fix kubeedge cloudcore component advertiseAddress configuration format error
  roles/kubeedge/files/kubeedge/kubeedge/templates/configmap_kubeedge.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1535 update: fluentbit-config add resource config
  roles/common/templates/custom-fluentbit-fluentBit.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1536 Add preset CSI Provisioner CRs and remove mountpath of kubelet plugins
  roles/common/files/ks-crds/provisonercapability/disk-csi-qingcloud-com.yaml
  roles/common/files/ks-crds/provisonercapability/neonsan-csi-qingstor-com.yaml
  roles/ks-core/ks-core/templates/ks-controller-manager.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1537 Adjust limits for node exporter and kube-state-metrics
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
  roles/ks-monitor/templates/node-exporter-daemonset.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1539 tweak etcd selector for etcdHighNumberOfFailedGRPCRequests rule
  roles/ks-monitor/files/prometheus/etcd/prometheus-rulesEtcd.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1542 Update the official mirror address for kubeedge v1.6.2
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1534 fix: Fix workspace settings alias duplicate
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1548 update workflow for release-3.1
  .github/workflows/pr-test.yml
Labels: approved, dco-signoff: yes, size/S

#1545 [release-3.1] combine some feature fixes by cherry-pick
  deploy/cluster-configuration.yaml
  roles/download/defaults/main.yml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/prometheus-stack.yaml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#1552 Update the default version to release-3.1
  deploy/kubesphere-installer.yaml
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, size/S

#1551 Fix workspace admin cannot view workspace resource quotas
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1557 fix push image
  .github/workflows/e2e-TEST.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1556 fix selector for kube_node_status_allocatable_memory_bytes and kube_resourcequota
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: dco-signoff: yes, lgtm, size/S

#1558 fix push images
  .github/workflows/e2e-TEST.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1565 Update pods/exec rules in roletemplates.yaml
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1562 Unify the beginning of the script
  scripts/offline-installation-tool.sh
  scripts/sync-images.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1563 fix bug notification manager config will be reset after installer res…
  roles/ks-monitor/tasks/notification-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1564 fix bug notification manager config will be reset after installer res…
  roles/ks-monitor/tasks/notification-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1561 [release 3.1]cherry-pick #1533, fix kubeedge cloudcore component advertiseAddress configuration format error
  roles/kubeedge/files/kubeedge/kubeedge/templates/configmap_kubeedge.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1571 delete old op job when update tag of image && update images tag of op-job
  roles/download/defaults/main.yml
  roles/openpitrix/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1573 [Manual cherrypick] delete old op job when update tag of image && update images tag of op-job
  roles/download/defaults/main.yml
  roles/openpitrix/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1576 Support for upgrade
  controller/installRunner.py
  roles/check-result/tasks/main.yaml
  roles/download/defaults/main.yml
  roles/ks-core/ks-core/defaults/main.yaml
  roles/ks-core/prepare/defaults/main.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/thanosruler.yaml
  roles/telemetry/tasks/main.yaml
Labels: approved, dco-signoff: no, size/L

#1578 Support for automatic upgrade
  controller/installRunner.py
  roles/check-result/tasks/main.yaml
  roles/download/defaults/main.yml
  roles/ks-core/ks-core/defaults/main.yaml
  roles/ks-core/prepare/defaults/main.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/prometheus-stack.yaml
  roles/ks-monitor/tasks/thanosruler.yaml
  roles/telemetry/tasks/main.yaml
Labels: approved, dco-signoff: yes, size/L
