Repository kubesphere/ks-installer, pull requests merged in 2021-02, with the labels that each got.

#1250 improvement: allow failed to destroy iaas
  .github/workflows/deploy-weekly.yml
Labels: dco-signoff: yes, lgtm, size/XS

#1249 integration of custom alerting
  deploy/cluster-configuration.yaml
  playbooks/alerting.yaml
  roles/common/tasks/init-namespaces.yaml
  roles/download/defaults/main.yml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-monitor/files/prometheus/thanosruler/thanosruler.yaml
  roles/ks-monitor/tasks/generate_manifests.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/thanosruler.yaml
  roles/ks-monitor/templates/thanosruler.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/L

#1254 Unify the writing of the name: KubeSphere & Kubesphere
  roles/common/tasks/common-install.yaml
  roles/common/tasks/es-install.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/tasks/get_old_config.yaml
  roles/common/tasks/init-namespaces.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/minio-install.yaml
  roles/common/tasks/minio-migration.yaml
  roles/common/tasks/mysql-install.yaml
  roles/common/tasks/openldap-install.yaml
  roles/common/tasks/openldap-migration.yaml
  roles/common/tasks/pv-migration.yaml
  roles/common/tasks/redis-install.yaml
  roles/common/tasks/redis-migration.yaml
  roles/ks-core/init-token/tasks/main.yaml
  roles/ks-core/prepare/tasks/ks-init.yaml
  roles/ks-core/prepare/tasks/main.yaml
  roles/ks-multicluster/tasks/main.yml
  roles/preinstall/tasks/helm-migrate.yaml
  roles/preinstall/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1255 Unify the name in [k8s / kubernetes] and [storage class / StorageClass] …
  roles/common/tasks/es-install.yaml
  roles/common/tasks/mysql-install.yaml
  roles/download/tasks/sync_container.yml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-auditing/tasks/main.yaml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/init-token/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/prepare/tasks/ks-stop.yaml
  roles/ks-events/tasks/main.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-multicluster/tasks/main.yml
  roles/ks-notification/tasks/main.yaml
  roles/kubesphere-defaults/tasks/main.yaml
  roles/metrics-server/tasks/main.yml
  roles/openpitrix/tasks/main.yaml
  roles/preinstall/tasks/precheck.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1256 Capitalize the first letter with kubernetes & Change Import to Importing
  README.md
  roles/common/files/minio-ha/README.md
  roles/common/files/minio-ha/values.yaml
  roles/common/tasks/es-install.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/minio-install.yaml
  roles/common/tasks/mysql-install.yaml
  roles/common/tasks/openldap-install.yaml
  roles/common/tasks/redis-install.yaml
  roles/common/templates/custom-values-minio.yaml.j2
  roles/download/defaults/main.yml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-auditing/tasks/main.yaml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-events/tasks/main.yaml
  roles/ks-logging/tasks/main.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-multicluster/tasks/main.yml
  roles/ks-network/topology/weave-scope/tasks/main.yaml
  roles/ks-notification/tasks/main.yaml
  roles/kubesphere-defaults/defaults/main.yaml
  roles/metrics-server/tasks/main.yml
  roles/openpitrix/tasks/main.yaml
  roles/preinstall/tasks/precheck.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1258 add default config for ippool
  deploy/cluster-configuration.yaml
  roles/ks-core/prepare/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1257 Standardize some nouns for monitoring module.
  roles/ks-monitor/tasks/alertmanager.yaml
  roles/ks-monitor/tasks/cleanup.yaml
  roles/ks-monitor/tasks/devops.yaml
  roles/ks-monitor/tasks/etcd.yaml
  roles/ks-monitor/tasks/generate_manifests.yaml
  roles/ks-monitor/tasks/get_old_config.yaml
  roles/ks-monitor/tasks/grafana.yaml
  roles/ks-monitor/tasks/kube-state-metrics.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/monitoring-dashboard.yaml
  roles/ks-monitor/tasks/node-exporter.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/tasks/prometheus-adapter.yaml
  roles/ks-monitor/tasks/prometheus-operator.yaml
  roles/ks-monitor/tasks/prometheus-rules.yaml
  roles/ks-monitor/tasks/prometheus.yaml
  roles/ks-monitor/tasks/thanosruler.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1259 Add network enable switch
  deploy/cluster-configuration.yaml
Labels: dco-signoff: yes, size/XS

#1260 Adjust ThanosRuler deployment
  roles/ks-monitor/files/prometheus/thanosruler/thanosruler.yaml
  roles/ks-monitor/templates/thanosruler.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1261 update notification manager to v1.0.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager/crds/emailconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/emailreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_dingtalkconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_dingtalkreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_emailconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_emailreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_slackconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_slackreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_webhookconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_webhookreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_wechatconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_wechatreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/crds/slackconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/slackreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/wechatconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/wechatreceivers.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterroles.yaml
  roles/ks-monitor/files/notification-manager/templates/namespace.yaml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/templates/operator.yaml
  roles/ks-monitor/files/notification-manager/templates/template.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
  roles/ks-multicluster/files/kubefed/federatedcrds/dingtalkconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/dingtalkreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/emailconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/emailreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/slackconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/slackreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/webhookconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/webhookreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/wechatconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/wechatreceivers.notification.kubesphere.io.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1262 Upgrade Prometheus to v2.25.0
  roles/download/defaults/main.yml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1263 Remove Jenkins update center in the next version
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/uninstall_update_center.yaml
  scripts/images-list.txt
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/S

#1264 Add KubeEdge installation package
  roles/kubeedge/files/kubeedge/Chart.yaml
  roles/kubeedge/files/kubeedge/crds/cluster_objectsync_v1alpha1.yaml
  roles/kubeedge/files/kubeedge/crds/devices_v1alpha2_device.yaml
  roles/kubeedge/files/kubeedge/crds/devices_v1alpha2_devicemodel.yaml
  roles/kubeedge/files/kubeedge/crds/edge_watcher_iptables_v1alpha1.yaml
  roles/kubeedge/files/kubeedge/crds/edge_watcher_iptablesrules_v1alpha1.yaml
  roles/kubeedge/files/kubeedge/crds/objectsync_v1alpha1.yaml
  roles/kubeedge/files/kubeedge/templates/_helpers.tpl
  roles/kubeedge/files/kubeedge/templates/clusterrole_edge_watcher_manager.yaml
  roles/kubeedge/files/kubeedge/templates/clusterrole_edge_watcher_metricsreader.yaml
  roles/kubeedge/files/kubeedge/templates/clusterrole_edge_watcher_proxy.yaml
  roles/kubeedge/files/kubeedge/templates/clusterrole_kubeedge.yaml
  roles/kubeedge/files/kubeedge/templates/clusterrolebinding_edge_watcher_manager.yaml
  roles/kubeedge/files/kubeedge/templates/clusterrolebinding_edge_watcher_proxy.yaml
  roles/kubeedge/files/kubeedge/templates/clusterrolebinding_kubeedge.yaml
  roles/kubeedge/files/kubeedge/templates/configmap_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/templates/configmap_kubeedge.yaml
  roles/kubeedge/files/kubeedge/templates/deployment_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/templates/deployment_kubeedge.yaml
  roles/kubeedge/files/kubeedge/templates/iptables.yaml
  roles/kubeedge/files/kubeedge/templates/role_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/templates/rolebinding_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/templates/secret_kubeedge.yaml
  roles/kubeedge/files/kubeedge/templates/service_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/templates/service_kubeedge.yaml
  roles/kubeedge/files/kubeedge/templates/serviceaccount_kubeedge.yaml
  roles/kubeedge/files/kubeedge/values.yaml
  roles/kubeedge/tasks/main.yaml
  roles/kubeedge/templates/values.yaml.j2
Labels: approved, dco-signoff: no, lgtm, size/XXL

#1267 update kubeedge role
  deploy/kubesphere-installer.yaml
  roles/kubeedge/tasks/main.yaml
  roles/kubeedge/templates/custom-values-kubeedge.yaml.j2
  roles/kubeedge/templates/values.yaml.j2
Labels: approved, dco-signoff: yes, size/L

#1265 Upgrade metrics-server to v0.4.2
  roles/download/defaults/main.yml
  roles/metrics-server/files/metrics-server.yaml
  roles/metrics-server/files/metrics-server/.helmignore
  roles/metrics-server/files/metrics-server/Chart.yaml
  roles/metrics-server/files/metrics-server/OWNERS
  roles/metrics-server/files/metrics-server/README.md
  roles/metrics-server/files/metrics-server/ci/ci-values.yaml
  roles/metrics-server/files/metrics-server/templates/NOTES.txt
  roles/metrics-server/files/metrics-server/templates/_helpers.tpl
  roles/metrics-server/files/metrics-server/templates/aggregated-metrics-reader-cluster-role.yaml
  roles/metrics-server/files/metrics-server/templates/auth-delegator-crb.yaml
  roles/metrics-server/files/metrics-server/templates/cluster-role.yaml
  roles/metrics-server/files/metrics-server/templates/metric-server-service.yaml
  roles/metrics-server/files/metrics-server/templates/metrics-api-service.yaml
  roles/metrics-server/files/metrics-server/templates/metrics-server-crb.yaml
  roles/metrics-server/files/metrics-server/templates/metrics-server-deployment.yaml
  roles/metrics-server/files/metrics-server/templates/metrics-server-serviceaccount.yaml
  roles/metrics-server/files/metrics-server/templates/pdb.yaml
  roles/metrics-server/files/metrics-server/templates/psp.yaml
  roles/metrics-server/files/metrics-server/templates/role-binding.yaml
  roles/metrics-server/files/metrics-server/templates/tests/test-version.yaml
  roles/metrics-server/files/metrics-server/values.yaml
  roles/metrics-server/tasks/main.yml
  roles/metrics-server/templates/metrics-server.yaml.j2
  roles/metrics-server/templates/values.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XXL
