Repository kubesphere/ks-installer, pull requests merged in 2021-08, with the labels that each got.

#1598 bump kind-action to v1.2.0
  .github/workflows/e2e-TEST.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1575 Cleanup left clusterRole and clusterRoleBindings in kubesphere-delete.sh
  roles/common/tasks/init-namespaces.yaml
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1619 support for GPU monitoring installation
  deploy/cluster-configuration.yaml
  deploy/kubesphere-installer.yaml
  roles/ks-monitor/files/gpu-monitoring/gpu-dashboards/nvidia-gpu-dcgm-exporter-clusterdashboard.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/.helmignore
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/Chart.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/NOTES.txt
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/_helpers.tpl
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/daemonset.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/service-monitor.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/service.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/serviceaccount.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/values.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-device-plugin/nvidia-device-plugin.yml
  roles/ks-monitor/tasks/gpu-monitoring.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/templates/custom-values-gpu-monitoring.yaml.j2
Labels: approved, lgtm, size/XL

#1623 Revert "support for GPU monitoring installation"
  deploy/cluster-configuration.yaml
  deploy/kubesphere-installer.yaml
  roles/ks-monitor/files/gpu-monitoring/gpu-dashboards/nvidia-gpu-dcgm-exporter-clusterdashboard.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/.helmignore
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/Chart.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/NOTES.txt
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/_helpers.tpl
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/daemonset.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/service-monitor.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/service.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/serviceaccount.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/values.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-device-plugin/nvidia-device-plugin.yml
  roles/ks-monitor/tasks/gpu-monitoring.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/templates/custom-values-gpu-monitoring.yaml.j2
Labels: approved, size/XL

#1612 Fix: add missing monitoring-dashboard CRD files while specifying an existing Prometheus stack during installation
  roles/ks-monitor/tasks/generate_manifests.yaml
  roles/ks-monitor/tasks/monitoring-dashboard.yaml
  roles/ks-monitor/tasks/prometheus-stack.yaml
Labels: approved, lgtm, size/S

#1626 Sync ks-core helm chart
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-controller-manager.yaml
  roles/ks-core/ks-core/files/ks-core/templates/ks-router-config.tpl
  roles/ks-core/ks-core/files/ks-core/templates/sample-bookinfo-configmap.yaml
  roles/ks-core/ks-core/files/ks-core/values.yaml
Labels: approved, kind/flake, lgtm, size/S

#1624 support for GPU monitoring installation
  deploy/cluster-configuration.yaml
  deploy/kubesphere-installer.yaml
  roles/ks-monitor/files/gpu-monitoring/gpu-dashboards/nvidia-gpu-dcgm-exporter-clusterdashboard.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/.helmignore
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/Chart.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/NOTES.txt
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/_helpers.tpl
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/daemonset.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/service-monitor.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/service.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/templates/serviceaccount.yaml
  roles/ks-monitor/files/gpu-monitoring/nvidia-dcgm-exporter/values.yaml
  roles/ks-monitor/tasks/gpu-monitoring.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/templates/custom-values-gpu-monitoring.yaml.j2
Labels: approved, lgtm, size/XL

#1630 bump kubefed-kubectl version to v1.19.1
  roles/download/defaults/main.yml
Labels: size/XS

#1627 Secure Redis connection between ks-apiserver
  roles/common/files/redis-ha/templates/_configs.tpl
  roles/common/files/redis-ha/templates/redis-haproxy-deployment.yaml
  roles/common/tasks/redis-install.yaml
  roles/common/templates/custom-values-redis.yaml.j2
  roles/common/templates/redis.yaml.j2
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, lgtm, size/M

#1634 Improve the image tag name in the makefile
  .gitignore
  Makefile
Labels: approved, lgtm, size/XS

#1632 update admission webhook version to admissionregistration.k8s.io/v1
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
Labels: approved, lgtm, size/XS

#1635 feat: integrate Gatekeeper into ks-installer
  deploy/cluster-configuration.yaml
  playbooks/gatekeeper.yaml
  roles/download/defaults/main.yml
  roles/gatekeeper/files/gatekeeper/.helmignore
  roles/gatekeeper/files/gatekeeper/Chart.yaml
  roles/gatekeeper/files/gatekeeper/README.md
  roles/gatekeeper/files/gatekeeper/crds/assign-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/crds/assignmetadata-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/crds/config-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/crds/constraintpodstatus-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/crds/constrainttemplate-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/crds/constrainttemplatepodstatus-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/crds/mutatorpodstatus-customresourcedefinition.yaml
  roles/gatekeeper/files/gatekeeper/templates/_helpers.tpl
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-admin-podsecuritypolicy.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-admin-serviceaccount.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-audit-deployment.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-controller-manager-deployment.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-controller-manager-poddisruptionbudget.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-critical-pods-resourcequota.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-manager-role-clusterrole.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-manager-role-role.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-manager-rolebinding-clusterrolebinding.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-manager-rolebinding-rolebinding.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-webhook-server-cert-secret.yaml
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-webhook-service-service.yaml
  roles/gatekeeper/files/gatekeeper/templates/namespace-post-install.yaml
  roles/gatekeeper/files/gatekeeper/values.yaml
  roles/gatekeeper/tasks/main.yaml
  roles/gatekeeper/templates/custom-values-gatekeeper.yaml.j2
Labels: approved, lgtm, size/XXL

#1639 upgrade logsidecar admission webhook version to v1
  roles/ks-logging/files/logsidecar-injector/templates/admission.yaml
Labels: approved, lgtm, size/XS

#1638 kubeedge: fix NodeIp when ks-installer resync
  roles/kubeedge/tasks/main.yaml
Labels: approved, lgtm, size/XS

#1637 Fix failed to enable workspace network isolation
  roles/ks-core/ks-core/files/ks-core/crds/tenant.kubesphere.io_workspacetemplates.yaml
Labels: size/XS

#1640 upgrade kube-events admission webhook version to v1
  roles/ks-events/files/kube-events/templates/operator/admission.yaml
Labels: approved, lgtm, size/S

#1644 Update ks-core main, remove capability CRD and file
  roles/common/files/ks-crds/provisonercapability/disk-csi-qingcloud-com.yaml
  roles/common/files/ks-crds/provisonercapability/neonsan-csi-qingstor-com.yaml
  roles/ks-core/ks-core/files/ks-core/crds/storage.kubesphere.io_provisionercapabilities.yaml
  roles/ks-core/ks-core/files/ks-core/crds/storage.kubesphere.io_storageclasscapabilities.yaml
  roles/ks-core/prepare/files/provisonercapability/aws-ebs.yaml
  roles/ks-core/prepare/files/provisonercapability/azure-disk.yaml
  roles/ks-core/prepare/files/provisonercapability/azure-file.yaml
  roles/ks-core/prepare/files/provisonercapability/cinder.yaml
  roles/ks-core/prepare/files/provisonercapability/gce-pd.yaml
  roles/ks-core/prepare/files/provisonercapability/glusterfs.yaml
  roles/ks-core/prepare/files/provisonercapability/portworx-volume.yaml
  roles/ks-core/prepare/files/provisonercapability/rbd-csi-ceph.yaml
  roles/ks-core/prepare/files/provisonercapability/rbd-external.yaml
  roles/ks-core/prepare/files/provisonercapability/rbd.yaml
  roles/ks-core/prepare/tasks/main.yaml
Labels: approved, lgtm, size/L

#1642 Support custom components' resources
  controller/installRunner.py
  deploy/cluster-configuration.yaml
  playbooks/alerting.yaml
  roles/common/templates/custom-values-elasticsearch.yaml.j2
  roles/common/templates/custom-values-minio.yaml.j2
  roles/common/templates/custom-values-openldap.yaml.j2
  roles/common/templates/custom-values-redis.yaml.j2
  roles/common/templates/redis.yaml.j2
  roles/gatekeeper/templates/custom-values-gatekeeper.yaml.j2
  roles/ks-alerting/defaults/main.yaml
  roles/ks-alerting/files/alerting/0-defaultrolebinding.yaml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-alerting/templates/1-executor.yaml.j2
  roles/ks-alerting/templates/2-watcher.yaml.j2
  roles/ks-alerting/templates/3-manager.yaml.j2
  roles/ks-alerting/templates/4-client.yaml.j2
  roles/ks-alerting/templates/alerting-db-ctrl-job.yaml.j2
  roles/ks-alerting/templates/alerting-db-init-job.yaml.j2
  roles/ks-auditing/templates/custom-values.yaml.j2
  roles/ks-events/templates/custom-values-events.yaml.j2
  roles/ks-logging/templates/custom-values-logsidecar-injector.yaml.j2
  roles/ks-monitor/templates/alertmanager-alertmanager.yaml.j2
  roles/ks-monitor/templates/custom-values-gpu-monitoring.yaml.j2
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
  roles/ks-monitor/templates/node-exporter-daemonset.yaml.j2
  roles/ks-monitor/templates/prometheus-adapter-deployment.yaml.j2
  roles/ks-monitor/templates/prometheus-operator-deployment.yaml.j2
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
  roles/ks-notification/defaults/main.yaml
  roles/ks-notification/files/notification/notification-db-ctrl-job.yaml
  roles/ks-notification/files/notification/notification-db-init-job.yaml
  roles/ks-notification/files/notification/notification.yaml
  roles/ks-notification/tasks/main.yaml
  roles/ks-notification/tasks/save-config.yaml
  roles/ks-notification/templates/notification-db-ctrl-job.yaml.j2
  roles/ks-notification/templates/notification-db-init-job.yaml.j2
  roles/ks-notification/templates/notification.yaml.j2
Labels: approved, do-not-merge/work-in-progress, size/XXL

#1647 update GPU monitoring dashboard && upgrade kubeedge version to v1.7.2
  roles/download/defaults/main.yml
  roles/ks-monitor/files/gpu-monitoring/gpu-dashboards/nvidia-gpu-dcgm-exporter-clusterdashboard.yaml
  roles/kubeedge/files/kubeedge/kubeedge/templates/role_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  scripts/images-list.txt
Labels: approved, lgtm, size/L

#1648 upgrade cc CRD version from v1beta1 to v1
  deploy/kubesphere-installer.yaml
Labels: approved, size/S

#1649 Fix the nightly build image version
  .github/workflows/nightly-builds.yml
  deploy/cluster-configuration.yaml
Labels: approved, size/XS
