Repository kubesphere/ks-installer, pull requests merged in 2021-04, with the labels that each got.

#1367 Change scheduler & controller-manager port to https
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceKubeControllerManager.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceKubeScheduler.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceMonitorKubeControllerManager.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceMonitorKubeScheduler.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1368 Upgrade kube-state-metrics to v1.9.7
  roles/download/defaults/main.yml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#1364 import app or upgrade openpitrix
  controller/installRunner.py
  playbooks/openpitrix.yaml
  roles/common/tasks/init-namespaces.yaml
  roles/download/defaults/main.yml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/openpitrix/files/openpitrix/ks-openpitrix-import.yaml
  roles/openpitrix/files/openpitrix/openpitrix/.helmignore
  roles/openpitrix/files/openpitrix/openpitrix/Chart.yaml
  roles/openpitrix/files/openpitrix/openpitrix/templates/openpitrix-hyperpitrix-service.yaml
  roles/openpitrix/files/openpitrix/openpitrix/templates/openpitrix-hyperpitrix.yaml
  roles/openpitrix/files/openpitrix/openpitrix/values.yaml
  roles/openpitrix/tasks/main.yaml
  roles/openpitrix/templates/custom-values-openpitrix.yaml.j2
  roles/openpitrix/templates/hyperpitrix-generate-kubeconfig-job.yaml.j2
  roles/openpitrix/templates/ks-openpitrix-import.yaml.j2
  roles/openpitrix/templates/ks-openpitrix-upgrade.yaml.j2
  roles/openpitrix/templates/openpitrix-release-app-job.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1369 upgrade kubefed charts to v0.7.0
  roles/ks-multicluster/files/kubefed/kubefed/Chart.yaml
  roles/ks-multicluster/files/kubefed/kubefed/Chart.yaml.backup
  roles/ks-multicluster/files/kubefed/kubefed/README.md
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/Chart.yaml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/crds/crds.yaml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/templates/deployments.yaml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/templates/kubefedconfig.yaml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/templates/post-install-job.yaml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/templates/service.yaml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/templates/webhook.yaml
  roles/ks-multicluster/files/kubefed/kubefed/crds/crds.yaml
  roles/ks-multicluster/files/kubefed/kubefed/requirements.yaml
  roles/ks-multicluster/files/kubefed/kubefed/values.yaml
  roles/ks-multicluster/files/kubefed/kubefed/values.yaml.backup
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1370 update tower tag to latest
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1371 Update role template.
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1372 Update user CRD
  roles/common/files/ks-crds/iam.kubesphere.io_users.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1373 Update uninstall script
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#1376 support custom oauthOptions
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/XS

#1375 kubeedge: modify container name && command
  roles/kubeedge/files/kubeedge/kubeedge/templates/deployment_edge_watcher.yaml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#1377 execute network tasks
  controller/installRunner.py
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, size/XS

#1374 alerting rules migration
  roles/download/defaults/main.yml
  roles/ks-monitor/files/alerting-migration/ks-alerting-migration.yaml
  roles/ks-monitor/tasks/ks-alerting-migration.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/templates/ks-alerting-migration.yaml.j2
Labels: approved, area/alerting, dco-signoff: no, lgtm, size/L

#1378 Fix fluent-bit operator output auth fields error
  roles/common/tasks/es-install.yaml
  roles/common/tasks/main.yaml
  roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-events/templates/custom-output-elasticsearch-events.yaml.j2
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, dco-signoff: no, lgtm, size/M

#1379 fix basicAuth parameters
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/S

#1380 upgrade events ruler version
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1381 Update role templates
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1382 minor: rename deploy weekly
  .github/workflows/deploy-weekly/kubesphere.tf
Labels: dco-signoff: yes, size/XS

#1383 Kubeedge: Set workspace for kubeedge
  roles/kubeedge/tasks/main.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1385 fix(network): disable probe process
  roles/ks-network/topology/weave-scope/templates/weave-scope.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1284 Provider a better default public Gitlab service name
  roles/ks-devops/jenkins/templates/jenkins-casc-config.yml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1386 Update role templates
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1387 Upgrade Prometheus to v2.26.0
  roles/download/defaults/main.yml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1388 Use kind to test pr with servicemesh
  .github/workflows/deploy-test/install.sh
  .github/workflows/deploy-test/kubesphere.tf
  .github/workflows/deploy-test/var.tf
  .github/workflows/pr-test.yml
  scripts/check_cluster_status.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#1384 Add serviceaccount role template
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1389 remove deploy test
  .github/workflows/deploy-test.yml
  .github/workflows/pr-test.yml
  scripts/check_cluster_status.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1390 adjust resource requests for kind test
  .github/workflows/pr-test.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1391 Add secret permission
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1392 Add rule_id to Alertmanager group_by config
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-secret.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1393 delete helm release
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#1394 Add a section to introduce how to test the ks-installer
  CONTRIBUTING.md
  Makefile
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1397 modify image pullPolicy
  .github/workflows/pr-test.yml
  roles/common/files/ks-crds/servicemesh.kubesphere.io_servicepolicies.yaml
  roles/common/files/ks-crds/servicemesh.kubesphere.io_strategies.yaml
  roles/ks-istio/files/istio/readme.md
  roles/ks-istio/templates/custom-values-jaeger.yaml.j2
  roles/ks-istio/templates/custom-values-kiali.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1396 freeze s2i tag
  roles/download/defaults/main.yml
  roles/ks-devops/s2i/templates/s2ioperator.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1399 change the fluent-bit request and limit
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1402 update jwt secret generate script
  roles/ks-core/init-token/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1401 update kubefed custom-values-kubefed.yaml
  roles/download/defaults/main.yml
  roles/ks-multicluster/templates/custom-values-kubefed.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1404 modify default image tag for fb-operator
  roles/download/defaults/main.yml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#1403 move openpitrix upgradation to ks-core/config
  roles/common/files/ks-crds/application.kubesphere.io_helmreleases.yaml
  roles/common/files/ks-crds/application.kubesphere.io_helmrepos.yaml
  roles/ks-core/config/files/openpitrix/ks-openpitrix-upgrade.yaml
  roles/ks-core/config/tasks/ks-restart.yaml
  roles/ks-core/config/templates/ks-openpitrix-upgrade.yaml.j2
  roles/openpitrix/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1406 Disabled metering module in cluser configuration.
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1409 Remove metering switch in cc.
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1405 Fix: delete crd federatednamespaces in namespace kubesphere-monitoring-fe…
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1412 Upgrade prometheus-operator to v0.42.1
  roles/download/defaults/main.yml
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-secret.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0podmonitorCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0probeCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0prometheusCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-clusterRole.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-deployment.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-service.yaml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-operator-serviceMonitor.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1411 Add openldap bootstrap ldif files
  roles/common/files/openldap-ha/templates/bootstrap.yaml
  roles/common/files/openldap-ha/templates/statefulset.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1408 add istio notes for canary upgrade
  .github/workflows/pr-test.yml
  roles/check-result/templates/welcome.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1410 Mount metering price cm into ks-apiserver pod.
  roles/ks-core/ks-core/files/metering/metering-price.yml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/ks-core/templates/ks-apiserver.yml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1416 fix kind test
  .github/workflows/pr-test.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1415 Change openpitrix job restart policy
  roles/openpitrix/templates/ks-openpitrix-import.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1414 do alerting migration after ks-core/config
  roles/ks-core/config/files/alerting-migration/ks-alerting-migration.yaml
  roles/ks-core/config/tasks/ks-restart.yaml
  roles/ks-core/config/templates/ks-alerting-migration.yaml.j2
  roles/ks-monitor/tasks/ks-alerting-migration.yaml
  roles/ks-monitor/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1413 fix bug platform user can not set notification settings
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1421 Fix metering cm mount error.
  roles/ks-core/ks-core/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1418 redis and openldap aren't enabled by default
  controller/installRunner.py
  deploy/cluster-configuration.yaml
  roles/common/tasks/common-install.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/templates/ks-apiserver.yml.j2
Labels: approved, dco-signoff: yes, size/M

#1425 change openpitrix-jobs repo and tags
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1419 Fix prometheus-operator cannot list resource probes error
  roles/ks-monitor/files/prometheus/init/prometheus-operator-clusterRole.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1426 add description to system-workspace
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1400 fix: wrong json schema
  roles/common/files/ks-crds/storage.kubesphere.io_provisionercapabilities.yaml
  roles/common/files/ks-crds/storage.kubesphere.io_storageclasscapabilities.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1427 Remove metering ConfigMap dependency.
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/files/metering/metering-price.yml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/ks-core/templates/ks-apiserver.yml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1424 change servicemesh apis version
  .github/workflows/pr-test.yml
  roles/common/files/ks-crds/app.k8s.io_applications.yaml
  roles/common/files/ks-crds/servicemesh.kubesphere.io_servicepolicies.yaml
  roles/common/files/ks-crds/servicemesh.kubesphere.io_strategies.yaml
  roles/common/files/ks-crds/servicemesh_v1alpha2_servicepolicy.yaml
  roles/common/files/ks-crds/servicemesh_v1alpha2_strategy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1431 rbac.authorization.k8s.io/v1beta1 is going to removed on v1.22.0
  roles/ks-core/prepare/templates/kubesphere-controls-system.yaml.j2
  roles/kubeedge/files/kubeedge/kubeedge/templates/clusterrole_edge_watcher_metricsreader.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1433 remove old crds
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/files/ks-controller-manager/crds/app_v1beta1_application.yaml
  roles/ks-core/ks-core/files/ks-controller-manager/crds/servicemesh_v1alpha2_servicepolicy.yaml
  roles/ks-core/ks-core/files/ks-controller-manager/crds/servicemesh_v1alpha2_strategy.yaml
  roles/ks-core/ks-core/files/ks-controller-manager/crds/tenant_v1alpha1_workspace.yaml
  roles/ks-core/ks-core/files/ks-controller-manager/ks-controller-manager-svc.yaml
  roles/ks-core/ks-core/templates/ks-apiserver.yml.j2
  roles/ks-core/ks-core/templates/ks-controller-manager.yaml.j2
Labels: approved, dco-signoff: yes, size/XXL

#1434 adjust resource for kind test
  .github/workflows/pr-test.yml
  roles/ks-istio/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1428 fix bug Unable to receive alert notifications after upgrade
  roles/ks-monitor/files/notification-manager-migrator/backup_crds.sh
  roles/ks-monitor/files/notification-manager-migrator/update_crds.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1436 Fix comma splice
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1442 update redis and openldap's logic
  roles/common/tasks/common-install.yaml
  roles/common/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
Labels: approved, dco-signoff: yes, size/S

#1443 update Dockerfile
  Dockerfile
  Dockerfile.complete
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/M

#1432 Upgrade core crd version to v1
  roles/common/files/ks-crds/cluster.kubesphere.io_clusters.yaml
  roles/common/files/ks-crds/devops.kubesphere.io_devopsprojects.yaml
  roles/common/files/ks-crds/devops.kubesphere.io_pipelines.yaml
  roles/common/files/ks-crds/devops.kubesphere.io_s2ibinaries.yaml
  roles/common/files/ks-crds/devops.kubesphere.io_s2ibuilders.yaml
  roles/common/files/ks-crds/devops.kubesphere.io_s2ibuildertemplates.yaml
  roles/common/files/ks-crds/devops.kubesphere.io_s2iruns.yaml
  roles/common/files/ks-crds/devops_v1alpha1_s2ibinary.yaml
  roles/common/files/ks-crds/devops_v1alpha1_s2ibuilder.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_globalrolebindings.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_globalroles.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_groupbindings.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_groups.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_loginrecords.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_rolebases.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_workspacerolebindings.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_workspaceroles.yaml
  roles/common/files/ks-crds/network.kubesphere.io_ipamblocks.yaml
  roles/common/files/ks-crds/network.kubesphere.io_ipamhandles.yaml
  roles/common/files/ks-crds/network.kubesphere.io_ippools.yaml
  roles/common/files/ks-crds/network.kubesphere.io_namespacenetworkpolicies.yaml
  roles/common/files/ks-crds/quota.kubesphere.io_resourcequotas.yaml
  roles/common/files/ks-crds/storage.kubesphere.io_provisionercapabilities.yaml
  roles/common/files/ks-crds/storage.kubesphere.io_storageclasscapabilities.yaml
  roles/common/files/ks-crds/tenant.kubesphere.io_workspaces.yaml
  roles/common/files/ks-crds/tenant.kubesphere.io_workspacetemplates.yaml
  roles/common/files/ks-crds/tenant_v1alpha1_workspace.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/applications.app.k8s.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/clusterrolebindings.rbac.authorization.k8s.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/clusterroles.rbac.authorization.k8s.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/configmaps.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/deployments.apps.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/globalrolebindings.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/globalroles.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/groupbindings.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/groups.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/jobs.batch.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/limitranges.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/namespaces.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/persistentvolumeclaims.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/replicasets.apps.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/secrets.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/serviceaccounts.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/services.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/statefulsets.apps.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/users.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/workspacerolebindings.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/workspaceroles.iam.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/workspaces.tenant.kubesphere.io.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1438 Fix system-workspace shouldn't be controled by kubefed
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1441 Update s2i admission webhook server certs
  roles/ks-devops/s2i/templates/s2ioperator.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1449 add kubeedge images
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#1447 upgrade kube-rbac-proxy to v0.8.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/prometheus/init/prometheus-operator-deployment.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-daemonset.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#1448 fix bug notification manager upgrade failed
  roles/ks-monitor/files/notification-manager-migrator/deploy.sh
  roles/ks-monitor/files/notification-manager-migrator/update.sh
  roles/ks-monitor/tasks/notification-manager.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: no, size/S

#1446 upgrade events and monitoring dashboard crds apiextensions to v1
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_exporters.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rulers.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rules.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-clusterdashboard-customResourceDefinition.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-dashboard-customResourceDefinition.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1451 change ingress controller image
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1450 Limit the maximum name length
  roles/common/files/ks-crds/iam.kubesphere.io_globalroles.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_groups.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_users.yaml
  roles/common/files/ks-crds/iam.kubesphere.io_workspaceroles.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1444 delete namespace openpitrix-system && change openpitrix-jobs tag
  roles/download/defaults/main.yml
  roles/ks-core/config/tasks/ks-restart.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1452 add RawExtension type annotation
  roles/common/files/ks-crds/iam.kubesphere.io_rolebases.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1453 Fix kube-rbac-proxy security context
  roles/ks-monitor/files/prometheus/init/prometheus-operator-deployment.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-daemonset.yaml
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
  roles/ks-monitor/templates/node-exporter-daemonset.yaml.j2
  roles/ks-monitor/templates/prometheus-operator-deployment.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1454 enable logging test && fix timeout
  .github/workflows/kind/kind.yaml
  .github/workflows/pr-test.yml
  scripts/check_cluster_status.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#1455 Revert "upgrade events and monitoring dashboard crds apiextensions to v1"
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_exporters.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rulers.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rules.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-clusterdashboard-customResourceDefinition.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-dashboard-customResourceDefinition.yaml
Labels: approved, dco-signoff: no, size/XXL

#1457 upgrade dashboard and events crd apiextensions version to v1
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_exporters.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rulers.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rules.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-clusterdashboard-customResourceDefinition.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-dashboard-customResourceDefinition.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1460 add openssl to Dockerfile
  Dockerfile.complete
Labels: approved, dco-signoff: yes, size/XS

#1456 add annotation for workspacetemplate crd
  roles/common/files/ks-crds/tenant.kubesphere.io_workspacetemplates.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1459 fix docker push
  .github/workflows/docker-publish.yml
  .github/workflows/pr-test.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1462 push to dockerhub just trigger by kubesphere/ks-installer
  .github/workflows/pr-test.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1461 Update openpitrix jobs tag
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1464 change job name && import app after upgrade
  roles/ks-core/config/templates/ks-openpitrix-upgrade.yaml.j2
  roles/openpitrix/files/openpitrix/ks-openpitrix-import.yaml
  roles/openpitrix/templates/ks-openpitrix-import.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1466 add mysql configuration when OP is migrated
  roles/ks-core/config/tasks/ks-restart.yaml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/M

#1463 add leader election for tower proxy
  roles/ks-multicluster/templates/tower.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1467 Update s2i admission webhook server certs
  roles/ks-devops/s2i/files/s2i/certs.sh
  roles/ks-devops/s2i/tasks/main.yaml
  roles/ks-devops/s2i/templates/s2ioperator.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/L

#1470 Update openpitrix to v3.1.0
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1471 freeze tower tag to v0.2.0
  roles/download/defaults/main.yml
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/templates/post-install-job.yaml
  roles/ks-multicluster/templates/custom-values-kubefed.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1472 use kubesphere images
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, size/S

#1473 Change the docker hub org of devops from kubespheredev to kubesphere
  roles/download/defaults/main.yml
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/S

#1474 use kubesphere images
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, size/XS

#1468 Fix namespace:pvc_bytes_total:sum promql many-to-many error.
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1475 fix node:pod recording rules many-to-many error
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1476 Add initContainer to op job
  roles/openpitrix/templates/ks-openpitrix-import.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1478 update thanos image
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, size/XS

#1477 Update image list for o11y
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#1479 change kiali image policy to IfNotPresent
  roles/ks-istio/templates/kiali-cr.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1458 Correct patch content for plugin test step in pr-test.yml
  .github/workflows/pr-test.yml
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1482 update image repo
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1481 freeze kubefed helm post install job image tag
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1483 update release-3.1 images for tag v3.1.0
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#1484 Update weave scope image
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1485 remove unused images
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/M

#1480 Delete monitoring upgrade script from 2.1 to 3.0
  roles/ks-monitor/files/prometheus/upgrade/prometheus-system-pvc-cleanup.yaml.j2
  roles/ks-monitor/tasks/generate_manifests.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/templates/prometheus-system-pvc-cleanup.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1486 Update create_project_harbor.sh in accordance with images-list.txt
  scripts/create_project_harbor.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1487 remove unused notification manager images
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/M

#1488 update images list
  deploy/cluster-configuration.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/L

#1489 update image to v3.1.0
  deploy/kubesphere-installer.yaml
Labels: approved, dco-signoff: yes, size/XS

#1492 e2e test muliticluster
  .github/workflows/pr-test.yml
Labels: dco-signoff: yes, size/XS

#1494 Revert "e2e test muliticluster"
  .github/workflows/pr-test.yml
Labels: approved, dco-signoff: no

#1497 Add more version images of kubectl
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/XS

#1496 update readme
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#1495 freeze kubefed webhook tag
  roles/ks-multicluster/tasks/main.yml
  roles/ks-multicluster/templates/custom-values-kubefed.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1493 fix istiod hpa
  roles/common/tasks/fluentbit-install.yaml
  roles/ks-istio/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1498 Add node uname&network metrics
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-serviceMonitor.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1500 dos2unix with grafana-pvc.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-pvc.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
