Repository kubesphere/ks-installer, pull requests merged in 2021-01, with the labels that each got.

#1218 Add metering group in role templates.
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1221 update kubesphere-delete.sh
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#1222 Add group role template
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1223 fix: Using tcp check instead of http get
  roles/ks-core/ks-core/templates/ks-console-deployment.yml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1225 add clusterdashboard crd for monitoring with cluster level
  roles/ks-monitor/files/monitoring-dashboard/monitoring-clusterdashboard-customResourceDefinition.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1224 Add ippool-related crd
  playbooks/network.yaml
  playbooks/weave_scope.yaml
  roles/common/files/ks-crds/network.kubesphere.io_ipamblocks.yaml
  roles/common/files/ks-crds/network.kubesphere.io_ipamhandles.yaml
  roles/common/files/ks-crds/network.kubesphere.io_ippools.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/prepare/files/ks-init/network.kubesphere.io.yaml
  roles/ks-network/topology/weave-scope/files/weave-scope/weave-scope.yaml
  roles/ks-network/topology/weave-scope/tasks/main.yaml
  roles/ks-network/topology/weave-scope/templates/weave-scope.yaml.j2
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#1227 improvement: set os disk size
  .github/workflows/deploy-test/kubesphere.tf
  .github/workflows/deploy-weekly/kubesphere.tf
Labels: dco-signoff: yes, size/XS

#1228 Fix deleting member cluster when deleting host cluster KubeSphere
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#1229 Prompt when adding delete
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, size/M

#1232 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1231 fix: modify var [kubesphere_component_pod]
  roles/preinstall/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1234 install istio ingress-gateway
  deploy/cluster-configuration.yaml
  roles/ks-istio/templates/istio-profile.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1237 Change the initial letter of the log to uppercase in roles
  README_zh.md
  roles/common/tasks/fluentbit-install.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/minio-install.yaml
  roles/common/tasks/minio-migration.yaml
  roles/common/tasks/openldap-install.yaml
  roles/common/tasks/redis-install.yaml
  roles/ks-core/config/tasks/ks-restart.yaml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-monitor/tasks/cleanup.yaml
  roles/ks-network/topology/weave-scope/tasks/main.yaml
  roles/preinstall/tasks/precheck.yaml
  roles/telemetry/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1236 update kubesphere-delete
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1238 add s2i delete
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#1242 fix: wrong logging information at fluentbit-install.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/ks-logging/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1240 Update openpitrix version to v0.5.3
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1241 Update openpitrix version to v0.5.3
  roles/download/defaults/main.yml
Labels: dco-signoff: yes, lgtm, size/XS
