Repository kubesphere/ks-installer, pull requests merged in 2021-07, with the labels that each got.

#1579 Determine the status' type of clusterconfiguration
  controller/installRunner.py
Labels: approved, dco-signoff: yes, size/XS

#1570 Update role template rules of workspaces-manager
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1569 fix the scripts for creating harbor projects
  scripts/create_project_harbor.sh
  scripts/offline-installation-tool.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1574 Add dev_tag config in default cluster-configuration.yaml
  deploy/cluster-configuration.yaml
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1583 Fix the installition process of monitoring components
  roles/download/defaults/main.yml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/prometheus-stack.yaml
Labels: approved, dco-signoff: yes, size/M

#1582 Update the tag of op image
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1586 refine the installation process
  Dockerfile.complete
  controller/installRunner.py
  roles/ks-multicluster/tasks/main.yml
Labels: approved, dco-signoff: yes, size/S

#1585 support Harbor v2.0
  scripts/create_project_harbor.sh
Labels: approved, dco-signoff: no, lgtm, size/XS

#1588 update common images' version
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, size/XS

#1590 Add kubectl v1.20.x supports and update kubectl 1.19.0 to 1.19.1
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1593 fix events ruler upgrade
  roles/ks-events/tasks/main.yaml
Labels: dco-signoff: yes, size/S

#1595 Change kiali auth strategy to token
  roles/ks-istio/files/kiali/kiali-cr.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1592 Fix vertical privilege escalation
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1596 Fix: check variable is defined or not
  roles/openpitrix/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1600 update images list
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/M

#1602 [release-3.1] update images list
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/M

#1603 update kubectl image to v1.19.1
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/XS

#1605 update version to v3.1.1 at README.md
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1606 update the version of cc at cluster-configuration.yaml
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1608 Fix regression issue failed to login due to forbidden error
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#1610 update ansible and helm
  Dockerfile.complete
  roles/check-result/tasks/main.yaml
  roles/common/files/minio-ha/templates/deployment.yaml
  roles/common/files/openldap-ha/templates/statefulset.yaml
  roles/common/tasks/es-install.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/minio-install.yaml
  roles/common/tasks/minio-migration.yaml
  roles/common/tasks/mysql-install.yaml
  roles/common/tasks/openldap-install.yaml
  roles/common/tasks/openldap-migration.yaml
  roles/common/tasks/redis-install.yaml
  roles/common/tasks/redis-migration.yaml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-auditing/tasks/main.yaml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/prepare/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-devops/s2i/tasks/main.yaml
  roles/ks-events/tasks/main.yaml
  roles/ks-istio/tasks/jaeger-install.yaml
  roles/ks-istio/tasks/kiali-install.yaml
  roles/ks-istio/tasks/main.yaml
  roles/ks-logging/tasks/main.yaml
  roles/ks-migration/tasks/main.yaml
  roles/ks-monitor/tasks/cleanup.yaml
  roles/ks-monitor/tasks/devops.yaml
  roles/ks-monitor/tasks/etcd.yaml
  roles/ks-monitor/tasks/main.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/tasks/prometheus-operator.yaml
  roles/ks-monitor/tasks/prometheus.yaml
  roles/ks-monitor/tasks/thanosruler.yaml
  roles/ks-multicluster/tasks/main.yml
  roles/ks-network/topology/weave-scope/tasks/main.yaml
  roles/ks-notification/tasks/main.yaml
  roles/kubeedge/tasks/main.yaml
  roles/metrics-server/tasks/main.yml
Labels: approved, size/L

#1618 add host local time to kube-state-metrics
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
Labels: size/XS

#1615 Issue-1614: make the resource of ks-apiserver and ks-controller-manager pods configurabable
  deploy/cluster-configuration.yaml
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, lgtm, size/M
