Repository kubesphere/ks-installer, pull requests merged in 2021-03, with the labels that each got.

#1268 fix: uninstall kubesphere
  .github/workflows/deploy-test/install.sh
Labels: dco-signoff: yes, size/S

#1270 fix: shell error
  .github/workflows/deploy-test/install.sh
Labels: dco-signoff: yes, size/XS

#1271 fix: shell error
  .github/workflows/deploy-test/install.sh
  .github/workflows/deploy-test/kubesphere.tf
Labels: dco-signoff: yes, size/XS

#1269 Support Independent storage configuration for the monitoring module
  Dockerfile
  deploy/cluster-configuration.yaml
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1272 Fix metrics-server path error
  roles/metrics-server/files/metrics-server/metrics-server.yaml
Labels: dco-signoff: yes, lgtm, size/XS

#1273 feature: add ci
  .github/workflows/deploy-test/install.sh
  .github/workflows/docker-ci.yml
Labels: dco-signoff: yes, size/S

#1275 fix: deploy test
  .github/workflows/deploy-test/install.sh
Labels: dco-signoff: yes, size/S

#1276 Fix: permissions in dockerfile
  Dockerfile
Labels: dco-signoff: yes

#1274 Making logsidecar optional
  deploy/cluster-configuration.yaml
  playbooks/telemetry.yaml
  roles/ks-logging/defaults/main.yaml
  roles/ks-logging/tasks/logsidecar.yaml
  roles/ks-logging/tasks/main.yaml
  roles/ks-logging/templates/custom-values-logsidecar-injector.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1278 fix: disable kubeedge test
  .github/workflows/deploy-test/install.sh
Labels: dco-signoff: yes, size/XS

#1280 disable old notification
  playbooks/notification.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1283 support pr test
  .github/workflows/deploy-pr.yml
  .github/workflows/deploy-pr/install.sh
  .github/workflows/deploy-pr/kubesphere.tf
  .github/workflows/deploy-pr/var.tf
  .github/workflows/deploy-test.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1282 Optimize the log output format at tasks
  docs/IstioUpgradeGuide.md
  roles/common/tasks/es-install.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/tasks/get_old_config.yaml
  roles/common/tasks/init-namespaces.yaml
  roles/common/tasks/main.yaml
  roles/common/tasks/minio-install.yaml
  roles/common/tasks/minio-migration.yaml
  roles/common/tasks/openldap-install.yaml
  roles/common/tasks/openldap-migration.yaml
  roles/common/tasks/pv-migration.yaml
  roles/common/tasks/redis-install.yaml
  roles/common/tasks/redis-migration.yaml
  roles/download/defaults/main.yml
  roles/download/tasks/download_file.yml
  roles/download/tasks/download_prep.yml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-core/init-token/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/prepare/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/get_old_config.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-devops/s2i/tasks/main.yaml
  roles/ks-istio/tasks/jaeger-install.yaml
  roles/ks-istio/tasks/kiali-install.yaml
  roles/ks-istio/tasks/main.yaml
  roles/ks-istio/tasks/upgrade-pre.yaml
  roles/ks-migration/tasks/main.yaml
  roles/ks-multicluster/tasks/main.yml
  roles/ks-network/topology/weave-scope/tasks/main.yaml
  roles/ks-notification/tasks/main.yaml
  roles/kubesphere-defaults/defaults/main.yaml
  roles/openpitrix/tasks/main.yaml
  roles/preinstall/tasks/helm-migrate.yaml
  roles/preinstall/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1279 Add local_registry at ClusterConfiguration
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1285 support pr test
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes, size/S

#1286 fix docker image
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes, size/XS

#1287 fix docker login username
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes, size/XS

#1288 fix checkout code
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes, size/XS

#1289 fix checkout code
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes

#1290 use default branch
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes

#1291 fix terraform init
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes, size/XS

#1292 fix terraform
  .github/workflows/deploy-pr.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1294 add resource quota CRD
  roles/common/files/ks-crds/quota.kubesphere.io_resourcequotas.yaml
  roles/ks-core/prepare/files/ks-init/quota.kubesphere.io.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1295 add node-exporter nodeAffinity for edge node
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-daemonset.yaml
  roles/ks-monitor/templates/node-exporter-daemonset.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1281 Add comments to KubeEdge advertiseAddress
  deploy/cluster-configuration.yaml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  roles/kubeedge/templates/values.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1277 Change ServiceMonitorSelector back to empty
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1296 Add kubeedge option to kubesphere config
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1297 Add edge-watcher service, use affinity in deployments and daemonset
  roles/kubeedge/files/kubeedge/kubeedge/templates/deployment_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/kubeedge/templates/deployment_kubeedge.yaml
  roles/kubeedge/files/kubeedge/kubeedge/templates/iptables.yaml
  roles/kubeedge/files/kubeedge/kubeedge/templates/service_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  roles/kubeedge/templates/values.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1298 fix admission webhook API path
  roles/ks-core/prepare/files/ks-init/users.iam.kubesphere.io.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1299 Update kubeedge iptables CRD
  roles/kubeedge/files/kubeedge/kubeedge/crds/edge_watcher_iptables_v1alpha1.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1253 Upgrade nginx ingress controller version
  roles/download/defaults/main.yml
  roles/ks-core/ks-core/templates/ingress-controller.yaml.j2
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#1305 Optimize some log output format at roles
  roles/common/tasks/es-install.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/tasks/pv-migration.yaml
  roles/download/tasks/main.yml
  roles/download/tasks/sync_container.yml
  roles/ks-alerting/tasks/main.yaml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/prepare/tasks/ks-init.yaml
  roles/ks-core/prepare/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-monitor/tasks/generate_manifests.yaml
  roles/kubesphere-defaults/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1306 Release grafana support
  roles/download/defaults/main.yml
  roles/ks-monitor/tasks/generate_manifests.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1307 update notification manager to v2beta1
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/README.md
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_configs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_dingtalkconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_dingtalkreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_emailconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_emailreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_receivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_slackconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_slackreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_webhookconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_webhookreceivers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_wechatconfigs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_wechatreceivers.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterroles.yaml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1309 add application crds
  roles/common/files/ks-crds/application.kubesphere.io_helmapplications.yaml
  roles/common/files/ks-crds/application.kubesphere.io_helmapplicationversions.yaml
  roles/common/files/ks-crds/application.kubesphere.io_helmcategories.yaml
  roles/common/files/ks-crds/application.kubesphere.io_helmreleases.yaml
  roles/common/files/ks-crds/application.kubesphere.io_helmrepos.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1308 Add grafana's image pull at images-list.txt
  roles/common/tasks/openldap-migration.yaml
  roles/common/tasks/redis-migration.yaml
  roles/ks-core/config/tasks/ks-restart.yaml
  roles/ks-istio/tasks/upgrade-pre.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#1312 Update grafana configuration to new version (7.4.3)
  roles/ks-monitor/files/prometheus/grafana/grafana-configmap.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-dashboardDefinitions.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-pvc.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-serviceMonitor.yaml
  roles/ks-monitor/templates/grafana-deployment.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1310 move networkpolicy under network
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1300 Upgrade fluent-bit to v1.6.9 & fb operator to v0.4.0
  roles/common/files/fluentbit-operator/init/fluentbit-operator-clusterRole.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-filterCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-fluentbitCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-fluentbitconfigCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-inputCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-outputCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-parserCustomResourceDefinition.yaml
  roles/common/templates/custom-fluentbit-fluentBit.yaml.j2
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1301 Change kubectl image repo to kubesphere
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1313 fix: change grafana configmap's namespace to kubesphere-monitoring-system
  roles/ks-monitor/files/prometheus/grafana/grafana-dashboardDefinitions.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1316 update notification manager federated crds
  roles/ks-multicluster/files/kubefed/federatedcrds/configs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/dingtalkconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/dingtalkreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/emailconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/emailreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/receivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/slackconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/slackreceivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/webhookconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/wechatconfigs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/wechatreceivers.notification.kubesphere.io.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1314 add default envs for kubeedge-helms
  roles/download/defaults/main.yml
  roles/kubeedge/files/kubeedge/kubeedge/crds/devices_v1alpha1_device.yaml
  roles/kubeedge/files/kubeedge/kubeedge/crds/devices_v1alpha1_devicemodel.yaml
  roles/kubeedge/files/kubeedge/kubeedge/crds/edge_watcher_iptablesrules_v1alpha1.yaml
  roles/kubeedge/files/kubeedge/kubeedge/crds/router_v1_rule.yaml
  roles/kubeedge/files/kubeedge/kubeedge/crds/router_v1_ruleEndpoint.yaml
  roles/kubeedge/files/kubeedge/kubeedge/templates/deployment_edge_watcher.yaml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
Labels: approved, dco-signoff: no, lgtm, size/XL

#1317 Fix: "control characters are not allowed" error.
  roles/ks-monitor/files/prometheus/grafana/grafana-configmap.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1319 Fix: grafana's configuration error
  roles/ks-monitor/files/prometheus/grafana/grafana-dashboardDefinitions.yaml
  scripts/kubesphere-delete.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1320 support collect logs from docker and kubelet
  roles/common/files/fluentbit-operator/init/fluentbit-operator-configmap.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-parserCustomResourceDefinition.yaml
  roles/download/defaults/main.yml
  roles/ks-logging/files/fluentbit-operator/filter-systemd.yaml
  roles/ks-logging/files/fluentbit-operator/input-systemd-docker.yaml
  roles/ks-logging/files/fluentbit-operator/input-systemd-kubelet.yaml
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/L

#1322 fix resource quota admission webhook
  roles/ks-core/prepare/files/ks-init/iam.kubesphere.io.yaml
  roles/ks-core/prepare/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1318 Allows authenticated user access discovery apis
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1321 create bucket for openpitrix app store
  roles/common/templates/custom-values-minio.yaml.j2
Labels: approved, area/app-management, dco-signoff: yes, lgtm, size/XS

#1325 fix a bug for edgeWatcherAgent affinity
  roles/kubeedge/templates/values.yaml.j2
Labels: approved, dco-signoff: no, lgtm, size/S

#1245 Change the host path of maven and sonar cache dir to abs
  roles/ks-devops/jenkins/templates/jenkins-casc-config.yml.j2
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/S

#1328 remove old configuration
  deploy/cluster-configuration.yaml
  playbooks/openpitrix.yaml
  roles/common/tasks/common-install.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/L

#1327 add get attachments privilege
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1326 create federatednamespace kubesphere-monitoring-federated after mutil…
  deploy/kubesphere-installer.yaml
  roles/common/tasks/init-namespaces.yaml
  roles/ks-monitor/files/federated/federatednamespaces.yaml
  roles/ks-monitor/files/federated/kubesphere-monitoring-federated.yaml
  roles/ks-monitor/files/notification-manager/templates/namespace.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1331 conatiner log mount path
  roles/common/tasks/main.yaml
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
Labels: approved, dco-signoff: yes

#1330 Add endpoint config for alerting
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-monitor/templates/thanosruler.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1329 fix kubesphere/kubesphere#3297
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1334 Fix logic for deploying minio
  roles/common/tasks/common-install.yaml
Labels: approved, dco-signoff: yes

#1335 Support for custom openpitrix bucket
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/XS

#1337 Add alerting option
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1336 modify default image for kubeedge cloudcore
  roles/download/defaults/main.yml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1339 grant list node permission for authenticated users
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1338 Fix: resource yaml format error when ks_image_tag="" at cc
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1340 fix(network): disable weave net for weave scope
  roles/ks-network/topology/weave-scope/templates/weave-scope.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1302 Intergate metering module
  playbooks/metering.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1341 Revert "Fix: resource yaml format error when ks_image_tag="" at cc"
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: no, size/S

#1343 Auto Test PR with KIND
  .github/workflows/auto-test-pr.yml
  .github/workflows/deploy-pr.yml
  .github/workflows/deploy-pr/delete.sh
  .github/workflows/deploy-pr/install.sh
  .github/workflows/deploy-pr/kubesphere.tf
  .github/workflows/deploy-pr/var.tf
  .github/workflows/deploy-test.yml
  .github/workflows/deploy-weekly.yml
  .github/workflows/docker-ci.yml
  .github/workflows/nightly-builds.yml
  .github/workflows/test-pr.yml
  .github/workflows/update-pr.yml
  scripts/check_cluster_status.sh
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1344 Fix: fluent-bit Output template error
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1345 Modify logsidecar conditions
  roles/ks-logging/tasks/main.yaml
Labels: approved, dco-signoff: yes, size/XS

#1346 upgrade readme
  .github/workflows/auto-test-pr.yml
  roles/ks-istio/files/prometheus/readme.md
Labels: dco-signoff: yes, size/M

#1347 install istio ingress gateway by default
  .github/workflows/auto-test-pr.yml
  roles/ks-istio/files/istio/istio-profile-1.6.10.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1350 fix bug Unable to modify notification settings in console
  roles/ks-monitor/files/notification-manager/templates/operator.yaml
  roles/ks-monitor/files/notification-manager/templates/template.yaml
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-secret.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1333 Let ks-installer support optional configuration with authentication a…
  deploy/cluster-configuration.yaml
  roles/common/templates/custom-values-elasticsearch-curator.yaml.j2
  roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2
  roles/ks-events/templates/custom-output-elasticsearch-events.yaml.j2
  roles/ks-istio/tasks/jaeger-install.yaml
  roles/ks-istio/templates/jaeger-cr.yaml.j2
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/M

#1351 Standardize some nouns in ks-devops role configurations
  roles/ks-devops/jenkins/tasks/check_sonar.yaml
  roles/ks-devops/jenkins/tasks/get_old_config.yaml
  roles/ks-devops/jenkins/tasks/main.yaml
  roles/ks-devops/jenkins/tasks/sonar_token.yaml
  roles/ks-devops/jenkins/tasks/uninstall_update_center.yaml
  roles/ks-devops/meta/main.yaml
  roles/ks-devops/s2i/tasks/main.yaml
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1353 update external ElasticSearch logic
  roles/common/tasks/es-install.yaml
  roles/common/templates/custom-values-elasticsearch-curator.yaml.j2
  roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-events/templates/custom-output-elasticsearch-events.yaml.j2
  roles/ks-istio/tasks/jaeger-install.yaml
  roles/ks-istio/templates/jaeger-cr.yaml.j2
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, dco-signoff: yes, size/M

#1354 update runner logic
  controller/installRunner.py
Labels: approved, dco-signoff: yes, size/L

#1356 cluster configuration migration
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/metrics-server/tasks/main.yml
Labels: approved, dco-signoff: yes, size/S

#1357 update ks version
  roles/ks-core/ks-core/defaults/main.yaml
Labels: approved, dco-signoff: yes, size/XS

#1359 fix(network): update comment
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1358 modify default version for kubeedge
  roles/download/defaults/main.yml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1361 Add basicAuth configuration at kubesphere-config configmap
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/S

#1365 add mysql config for op migration
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: yes, size/S

#1366 Support to upgrade notification manager through installer
  roles/ks-monitor/files/notification-manager-migrator/backup_crds.sh
  roles/ks-monitor/files/notification-manager-migrator/update.sh
  roles/ks-monitor/files/notification-manager-migrator/update_crds.sh
  roles/ks-monitor/files/notification-manager/templates/operator.yaml
  roles/ks-monitor/files/notification-manager/templates/template.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1363 fix(network): label weave with system-workspace
  roles/ks-network/topology/weave-scope/templates/weave-scope.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1349 update bookinfo images
  roles/download/defaults/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1362 Fix: lost basicAuth configuration at kubesphere-config configmap
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, dco-signoff: no, lgtm, size/XS
