Repository kubesphere/ks-installer, pull requests merged in 2021-09, with the labels that each got.

#1658 Step by step CI testing
  .github/workflows/e2e-TEST.yml
  deploy/cluster-configuration.yaml
Labels: approved, size/M

#1650 Add support for external es using https
  roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-events/templates/custom-output-elasticsearch-events.yaml.j2
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, lgtm, size/M

#1652 use `jq -r` instead of sed
  roles/common/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/preinstall/tasks/precheck.yaml
Labels: approved, lgtm, size/XS

#1655 Cleanup left resources in namespace kubesphere-system & kubesphere-monitoring-system.
  scripts/kubesphere-delete.sh
Labels: approved, lgtm, size/XS

#1657 kubeedge: upgrade edge watcher tag to v0.1.1
  roles/download/defaults/main.yml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  scripts/images-list.txt
Labels: approved, lgtm, size/S

#1659 Delete code that fluentbit operator upgrade from v1alpha1 to v1alpha2
  roles/common/files/fluentbit-operator/migrator/migrator-rbac.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/templates/custom-migrator-job.yaml.j2
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/L

#1661 add comments for CI
  .github/workflows/e2e-TEST.yml
  roles/ks-istio/tasks/main.yaml
Labels: approved, size/M

#1663 support setting host cluster name
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, lgtm, size/XS

#1662 Change devops image tag from master to a variable ks_version
  roles/download/defaults/main.yml
Labels: approved, area/devops, lgtm, size/XS

#1668 Adjust the replica policy of the es
  .github/workflows/e2e-TEST.yml
  roles/common/templates/custom-values-elasticsearch.yaml.j2
  scripts/check_cluster_status.sh
Labels: approved, size/M

#1664 optimize the GPU-related monitoring && upgrade dashboards CRDs
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-monitor/files/monitoring-dashboard/monitoring-clusterdashboard-customResourceDefinition.yaml
  roles/ks-monitor/files/monitoring-dashboard/monitoring-dashboard-customResourceDefinition.yaml
Labels: lgtm, size/XXL

#1653 update fluentbit-operator
  deploy/cluster-configuration.yaml
  docs/vars.md
  roles/common/files/fluentbit-operator/init/fluentbit-operator-filterCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-fluentbitCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-fluentbitconfigCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-inputCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-outputCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-parserCustomResourceDefinition.yaml
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
  roles/download/defaults/main.yml
  roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2
  roles/ks-events/templates/custom-output-elasticsearch-events.yaml.j2
  roles/ks-logging/files/fluentbit-operator-cri/filter-containerd.yaml
  roles/ks-logging/files/fluentbit-operator-cri/fluentbit-containerd-config.yaml
  roles/ks-logging/tasks/main.yaml
  roles/ks-logging/templates/custom-input-logging.yaml.j2
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, lgtm, size/XXL

#1656 update notification manager to v1.3.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager-migrator/backup_crds.sh
  roles/ks-monitor/files/notification-manager-migrator/deploy.sh
  roles/ks-monitor/files/notification-manager-migrator/update.sh
  roles/ks-monitor/files/notification-manager-migrator/update_crds.sh
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_configs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_receivers.yaml
  roles/ks-monitor/files/notification-manager/templates/operator.yaml
  roles/ks-monitor/files/notification-manager/templates/services.yaml
  roles/ks-monitor/files/notification-manager/templates/template.yaml
  roles/ks-monitor/files/notification-manager/templates/tls.yaml
  roles/ks-monitor/files/notification-manager/templates/validating.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
Labels: approved, lgtm, size/XXL

#1669 sync ks-core charts from kubesphere repo
  roles/ks-core/ks-core/files/ks-core/crds/.gitkeep
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console-config.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-controller-manager.yaml
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
  roles/ks-core/ks-core/files/ks-core/values.yaml
Labels: approved, lgtm, size/L

#1670 Revert "sync ks-core charts from kubesphere repo"
  roles/ks-core/ks-core/files/ks-core/crds/.gitkeep
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console-config.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-controller-manager.yaml
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
  roles/ks-core/ks-core/files/ks-core/values.yaml
Labels: approved, size/L

#1673 fix misspelling in sync-images.sh
  scripts/sync-images.sh
Labels: approved, lgtm, size/XS

#1672 sync ks-core charts from kubesphere repo
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console-config.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-controller-manager.yaml
  roles/ks-core/ks-core/files/ks-core/values.yaml
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, lgtm, size/L

#1671 feat: add gpu kinds to configmap
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: lgtm, size/S

#1674 Use tenant sidecar to get receivers which will receive notifications
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
Labels: lgtm, size/S

#1675 collect containerruntime service log
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
  roles/ks-logging/tasks/main.yaml
  roles/ks-logging/templates/custom-input-logging.yaml.j2
  roles/ks-logging/templates/custom-input-systemd.yaml.j2
Labels: lgtm, size/S

#1677 fix: change the namespace of gatekeeper
  roles/gatekeeper/tasks/main.yaml
Labels: approved, lgtm, size/XS

#1678 Bump ks-devops helm chart from 0.1.0 to 0.1.1
  roles/ks-devops/files/ks-devops/charts/README.md
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.0.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.1.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/XS

#1682 Bump ks-devops chart version from 0.1.1 to 0.1.2
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.1.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.2.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/XS

#1683 Enable gateway featrue and sync ks-core chart
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/files/ks-core/crds/gateway.kubesphere.io_gateways.yaml
  roles/ks-core/ks-core/files/ks-core/crds/gateway.kubesphere.io_nginxes.yaml
Labels: approved, kind/feature, lgtm, size/L

#1684 revert GPU kinds
  deploy/cluster-configuration.yaml
Labels: lgtm, size/S

#1681 add notification-manager svc endpoint
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/files/ks-core/templates/kubesphere-config.yaml
  roles/ks-core/ks-core/files/ks-core/values.yaml
Labels: size/XS

#1685 Bump ks-devops chart version from 0.1.2 to 0.1.3
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.2.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.3.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, kind/bug, lgtm, size/XS

#1687 Refine configuration file
  controller/installRunner.py
  deploy/cluster-configuration.yaml
  roles/download/defaults/main.yml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, size/L

#1686 add client authentication configuration
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, lgtm, size/S

#1688 Remove extra spaces from the kubesphere-config
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, lgtm, size/XS

#1692 Fix the issue of invalid password after enable redis
  roles/ks-core/meta/main.yaml
Labels: approved, lgtm, size/XS

#1693 change admissionregistration version to v1
  roles/ks-monitor/files/federated/federatednamespaces.yaml
  roles/ks-monitor/files/notification-manager/templates/validating.yaml
Labels: approved, lgtm, size/L

#1690 fix clerical error: FluentBit ConfigMap
  roles/common/files/fluentbit-operator/init/fluentbit-operator-configmap.yaml
Labels: approved, lgtm, size/XS

#1694 change admissionregistration version to v1
  roles/ks-monitor/files/federated/federatednamespaces.yaml
  roles/ks-monitor/files/notification-manager/templates/validating.yaml
Labels: approved, lgtm, size/L

#1702 fix kubefed crd upgrade bug
  roles/ks-multicluster/files/kubefed/kubefed/charts/controllermanager/crds/crds.yaml
Labels: approved, lgtm, size/XS

#1698 Fix: don't execute kubeedge installation when kubernetes version >= 1.22
  roles/kubeedge/tasks/kubeedge.yaml
  roles/kubeedge/tasks/main.yaml
Labels: approved, lgtm, size/M

#1699 Make some resources of devops managed by helm
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/M

#1703 Remove unnecessary tag override
  roles/download/defaults/main.yml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, lgtm, size/M

#1706 Add linuxsuren as approver of the ks-devops
  roles/ks-devops/OWNERS
Labels: approved, area/devops, lgtm, size/XS

#1708 create builtin repo when installing app store
  deploy/kubesphere-installer.yaml
  roles/openpitrix/tasks/main.yaml
  roles/openpitrix/templates/builtin-repo.yaml.j2
Labels: approved, lgtm, size/M

#1710 Bump ks-devops chart from 0.1.3 to 0.1.4
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.3.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.4.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/XS

#1711 Fix the nightly tag of ks-devops apiserver,controller and tools
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, lgtm, size/XS

#1713 update notification manager to 1.4.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterrolebindings.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterroles.yaml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
Labels: approved, lgtm, size/M

#1712 update notification manager to 1.4.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterrolebindings.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterroles.yaml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
Labels: approved, lgtm, size/M

#1714 Sync ks-core helm chart
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console-config.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-controller-manager.yaml
  roles/ks-core/ks-core/files/ks-core/templates/sample-bookinfo-configmap.yaml
Labels: approved, lgtm, size/S

#1716 update image tag for branch master
  deploy/kubesphere-installer.yaml
Labels: approved, size/XS

#1726 Update volume size detection method
  controller/installRunner.py
  roles/common/tasks/get_old_config.yaml
  roles/ks-devops/tasks/get_old_config.yaml
  roles/ks-monitor/tasks/get_old_config.yaml
Labels: approved, size/M

#1728 Fix devops resources conversion task
  roles/ks-devops/tasks/main.yaml
Labels: approved, size/S

#1730 Avoid repeated creation of admin user
  roles/ks-core/ks-core/files/ks-core/templates/account.yaml
Labels: approved, lgtm, size/XS
