Repository kubesphere/ks-installer, pull requests merged in 2021-05, with the labels that each got.

#1504 Add tool for build an all-in-one images registry
  .github/workflows/build-images-registry.yml
  scripts/build/Dockerfile.registry
  scripts/build/Dockerfile.skopeo
  scripts/sync-images.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#1502 add enable kubeedge guide
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#1505 fix: Invalid value for `names`
  controller/installRunner.py
Labels: approved, dco-signoff: yes, size/XS

#1507 update image list
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, size/XS

#1508 Update logsidecar injector certs
  roles/ks-logging/files/logsidecar-injector/templates/admission.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1509 update weave scop template
  roles/ks-network/topology/weave-scope/templates/weave-scope.yaml.j2
Labels: approved, dco-signoff: yes, size/XS

#1510 fix servicemesh crd
  roles/common/files/ks-crds/servicemesh.kubesphere.io_strategies.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1513 fix istio webhook
  roles/ks-istio/tasks/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1516 Remove redundant selector field in kubeedge service
  roles/kubeedge/files/kubeedge/kubeedge/templates/service_kubeedge.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1518 fix namespace:pvc_bytes_total:sum rule
  roles/ks-monitor/files/prometheus/prometheus-rules-v1.16+.yaml
  roles/ks-monitor/files/prometheus/prometheus-rules.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1520 update devops image
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1521 Update installer desc
  deploy/cluster-configuration.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1524 Allow to debug ks-installer locally
  .gitignore
  controller/installRunner.py
  docs/DeveloperGuide.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#1522 fix servicemesh topology
  roles/common/files/ks-crds/servicemesh.kubesphere.io_servicepolicies.yaml
  roles/common/files/ks-crds/servicemesh.kubesphere.io_strategies.yaml
  roles/download/defaults/main.yml
  roles/ks-istio/files/prometheus/prometheus-additional.yaml
  roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1526 fix: incorrect pipeline logs
  .github/workflows/kind/kind.yaml
  .github/workflows/pr-test.yml
  scripts/check_cluster_status.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1527 upgrade kubeedge version to v1.6.2
  roles/download/defaults/main.yml
  roles/kubeedge/files/kubeedge/kubeedge/values.yaml
  scripts/images-list.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS
