Repository kubesphere/ks-installer, pull requests merged in 2021-11, with the labels that each got.

#1793 Bump ks-devops chart from 0.1.5 to 0.1.8
  roles/download/defaults/main.yml
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.5.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.8.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/S

#1796 update nginx-ingress-controller to v0.48.1
  roles/download/defaults/main.yml
Labels: approved, size/XS

#1797 Allows to override nginx ingress controller image in kubesphere config
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, kind/bug, lgtm, size/XS

#1801 Fix ks-core's replicas in the managed cluster is 0
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-console.yml
  roles/ks-core/ks-core/files/ks-core/templates/ks-controller-manager.yaml
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, lgtm, size/M

#1805 Update offline tools script
  scripts/offline-installation-tool.sh
Labels: approved, lgtm, size/M

#1798 Change externalElasticsearchUrl to externalElasticsearchHost at cc
  controller/installRunner.py
  deploy/cluster-configuration.yaml
  roles/common/defaults/main.yaml
  roles/common/tasks/es-install.yaml
  roles/common/templates/custom-values-elasticsearch-curator.yaml.j2
  roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-events/templates/custom-output-elasticsearch-events.yaml.j2
  roles/ks-istio/templates/jaeger-cr.yaml.j2
  roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2
Labels: approved, lgtm, size/M

#1807 default containerruntime is docker
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
  roles/ks-auditing/templates/custom-filter-auditing.yaml.j2
  roles/ks-auditing/templates/custom-input-auditing.yaml.j2
  roles/ks-events/templates/custom-filter-events.yaml.j2
  roles/ks-events/templates/custom-input-events.yaml.j2
  roles/ks-logging/templates/custom-input-logging.yaml.j2
Labels: approved, lgtm, size/M

#1800 fix(ks-istio/jaeger): fix secrets "jaeger-secret" already exists
  roles/ks-istio/tasks/jaeger-install.yaml
Labels: approved, lgtm, size/XS

#1819 Fix kubefed's kubectl image cannot be managed by ks-installer
  roles/ks-multicluster/templates/custom-values-kubefed.yaml.j2
Labels: approved, size/XS

#1817 Make DevOps agent runnable on containerd environment properly
  roles/ks-devops/tasks/main.yaml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, kind/feature, lgtm, size/S

#1822 modify es output plugin
  roles/ks-logging/tasks/main.yaml
Labels: approved, lgtm, size/XS

#1823 Update redis and haproxy version
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#1824 Fix bug install auditing failed after installer restart
  roles/ks-auditing/tasks/fluentbit-operator.yaml
  roles/ks-events/tasks/fluentbit-operator.yaml
Labels: approved, lgtm, size/S

#1828 Add role for crd pipelineruns
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/M

#1835 add examples in offline install script
  OWNERS
  scripts/offline-installation-tool.sh
Labels: approved, lgtm, size/S

#1834 Multiple components use the same kubectl image
  controller/installRunner.py
  roles/common/tasks/main.yaml
  roles/download/defaults/main.yml
  roles/ks-core/config/tasks/main.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-events/tasks/main.yaml
  roles/ks-monitor/tasks/prometheus-rules.yaml
  roles/ks-multicluster/tasks/main.yml
  roles/ks-multicluster/templates/custom-values-kubefed.yaml.j2
  roles/preinstall/tasks/precheck.yaml
Labels: approved, lgtm, size/M

#1831 Adjust default xmx/xms configuration
  deploy/cluster-configuration.yaml
Labels: approved, area/devops, lgtm, size/XS

#1833 Remove the default ingress for kiali and jaeger
  roles/ks-istio/templates/jaeger-cr.yaml.j2
  roles/ks-istio/templates/kiali-cr.yaml.j2
Labels: approved, lgtm, size/XS
