Repository kubesphere/ks-installer, pull requests merged in 2021-12, with the labels that each got.

#1841 Update RBAC rules of the project operator
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#1843 Add docker and crictl to offline-installation-tool.sh
  scripts/offline-installation-tool.sh
Labels: approved, lgtm, size/S

#1844 Bump up ks-devops helm charts
  roles/download/defaults/main.yml
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.8.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.9.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/M

#1845 Refine DevOps deletion
  scripts/kubesphere-delete.sh
Labels: approved, kind/optimization, lgtm, size/M

#1849 Refine PipelineRuns management and viewing roles
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, kind/bug, lgtm, size/S

#1848 Optimize DCGM Exporter installation
  deploy/cluster-configuration.yaml
  roles/ks-monitor/tasks/gpu-monitoring.yaml
  roles/ks-monitor/templates/custom-values-gpu-monitoring.yaml.j2
Labels: approved, lgtm, size/S

#1854 fix log4j2 bug
  roles/common/templates/custom-values-elasticsearch.yaml.j2
Labels: approved, lgtm, size/XS

#1856 patch kubeedge clusterrolebinding
  roles/kubeedge/files/kubeedge/kubeedge/templates/clusterrole_kubeedge.yaml
Labels: approved, lgtm, size/XS

#1860 update op image
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#1863 update op image
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#1867 Update the link address in the README
  README.md
  README_zh.md
Labels: approved, lgtm, size/S

#1840 Update users CRD
  roles/ks-core/ks-core/files/ks-core/crds/iam.kubesphere.io_users.yaml
Labels: approved, lgtm, size/XS

#1865 fix dcgm script
  roles/ks-monitor/tasks/gpu-monitoring.yaml
Labels: approved, lgtm, size/XS

#1873 Add read permission jenkins/labelsData to pipeline view role
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/XS
