Repository kubesphere/ks-installer, pull requests merged in 2022-05, with the labels that each got.

#1968 Fix the project-operator JSON format
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/XS

#1961 reuse values when upgrading argo-cd
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/XS

#1965 add edgeruntime configuration migration
  controller/installRunner.py
Labels: approved, lgtm, size/S

#1913 fixed the ks-install label in logs command in README.md
  README.md
Labels: approved, lgtm, size/XS

#1971 Support to configure extraVolumes for ks-console
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, lgtm, size/S

#1977 keep the old label 'app: ks-install'
  README.md
  README_zh.md
  deploy/kubesphere-installer.yaml
  docs/IstioUpgradeGuide.md
  scripts/check_cluster_status.sh
Labels: approved, lgtm, size/S

#1974 fix kubeedge nodeport
  roles/edgeruntime/files/kubeedge/cloudcore/templates/service_cloudcore.yaml
Labels: size/S

#1981 [release-3.3] fix Dockerfile wildcard character error
  Dockerfile.complete
  Dockerfile.shelloperator
Labels: approved, lgtm, size/XS

#1984 Fix the potential webhook-related issues
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/S

#1983 add remove old kubeedge task
  roles/edgeruntime/tasks/kubeedge.yaml
Labels: approved, lgtm, size/S

#1980 add redis enabledHA to cc
  deploy/cluster-configuration.yaml
  roles/common/tasks/common-install.yaml
  roles/common/tasks/redis-install.yaml
Labels: approved, lgtm, size/S

#1986 Avoid install s2i templates via the helm chart
  roles/ks-devops/tasks/main.yaml
Labels: approved, area/devops, lgtm, size/XS

#1989 Support to use an alternative image build tool
  Makefile
Labels: approved, lgtm, size/XS

#1993 restore some rule fixes
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-prometheusRule.yaml
Labels: approved, lgtm, size/XS

#1995 Bump Jenkins version to v3.3.0-2.319.1
  roles/download/defaults/main.yml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, lgtm, size/XS

#1997 Add gitops.kubesphere.io group to the global management role
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/XS

#1998 Add an anonymous API webhooks in DevOps
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#2002 update role-templates.yaml
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/L

#1996 Clean kubefed resources before uninstall
  scripts/kubesphere-delete.sh
Labels: approved, lgtm, size/S

#2004 add servicemesh configuration migration
  controller/installRunner.py
Labels: approved, lgtm, size/S
