Repository kubesphere/ks-installer, pull requests merged in 2022-04, with the labels that each got.

#1929 upgrade prometheus and prometheus-operator and thanos version
  roles/download/defaults/main.yml
  roles/ks-monitor/files/prometheus/etcd/prometheus-rulesEtcd.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-clusterRole.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-deployment.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-service.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-clusterRole.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-podDisruptionBudget.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheus.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-roleBindingConfig.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-roleConfig.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-service.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-podDisruptionBudget.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-service.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-thanosRuler.yaml
Labels: lgtm, size/M

#1925 Add Argo CD installation support
  roles/download/defaults/main.yml
  roles/ks-devops/defaults/main.yaml
  roles/ks-devops/files/ks-devops/charts/README.md
  roles/ks-devops/files/ks-devops/charts/argo-cd-4.4.0.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.10.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.9.tgz
  roles/ks-devops/tasks/main.yaml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, kind/feature, lgtm, size/M, tide/merge-method-squash

#1923 Update kubesphere-config.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, lgtm, size/S

#1915 Optimize data retention policies
  roles/common/templates/custom-values-elasticsearch-curator.yaml.j2
Labels: approved, lgtm, size/M

#1928 Add the resources required by the storageclass accessor
  roles/ks-core/ks-core/files/ks-core/crds/storage.kubesphere.io_storageclasseraccessor.yaml
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
Labels: approved, lgtm, size/L

#1933 Fix: Updated accessor CRD resources
  roles/ks-core/ks-core/files/ks-core/crds/storage.kubesphere.io_storageclasseraccessor.yaml
Labels: approved, lgtm, size/M

#1934 Refine installation logic
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-monitor/tasks/prometheus-operator.yaml
Labels: approved, lgtm, size/S

#1931 Install CRDs before installing or upgrading DevOps using Helm
  roles/download/defaults/main.yml
  roles/ks-devops/tasks/main.yaml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, lgtm, size/S

#1941 Update clusters.cluster.kubesphere.io CRD to latest version
  roles/ks-core/ks-core/files/ks-core/crds/cluster.kubesphere.io_clusters.yaml
Labels: approved, lgtm, size/M

#1939 Add image list of the Argo CD
  roles/download/defaults/main.yml
Labels: approved, area/devops, lgtm, size/M

#1940 Add offline image items for golang 17 and 18
  roles/download/defaults/main.yml
Labels: approved, area/devops, lgtm, size/M

#1942 Add roles for argo application and git repository
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/L

#1952 change some rule names
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-prometheusRule.yaml
Labels: lgtm, size/XS

#1953 revert prometheus service monitor selector
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheus.yaml
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: lgtm, size/XS

#1947 Fix the Jenkins inbound-agent image tag to 4.10-2
  roles/download/defaults/main.yml
Labels: approved, area/devops, lgtm, size/XS

#1948 Fix the missing permission of ks-devops
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/M

#1956 Remove the tasks of restarting ks-core
  roles/ks-core/config/tasks/ks-restart.yaml
Labels: approved, lgtm, size/S

#1962 fix devops's repo url
  roles/download/defaults/main.yml
Labels: approved, area/devops, lgtm, size/S

#1966 fix "namespace_override" for library
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS
