Repository kubesphere/ks-installer, pull requests merged in 2022-07, with the labels that each got.

#2042 remove \r
  scripts/offline-installation-tool.sh
Labels: approved, lgtm, size/XS

#2044 update notification manager to v2.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/federated/update_federated_crds.sh
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/crds/bundle.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_configs.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/crds/notification.kubesphere.io_receivers.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterrolebindings.yaml
  roles/ks-monitor/files/notification-manager/templates/clusterroles.yaml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/templates/post-install.yaml
  roles/ks-monitor/files/notification-manager/templates/roles.yaml
  roles/ks-monitor/files/notification-manager/templates/services.yaml
  roles/ks-monitor/files/notification-manager/templates/template.yaml
  roles/ks-monitor/files/notification-manager/templates/validating.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
  roles/ks-multicluster/files/kubefed/federatedcrds/configs.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/receivers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/routers.notification.kubesphere.io.yaml
  roles/ks-multicluster/files/kubefed/federatedcrds/silences.notification.kubesphere.io.yaml
Labels: approved, lgtm, size/XXL

#2045 fix bug logging output doesn't change when switching to external es
  roles/ks-logging/tasks/main.yaml
Labels: approved, lgtm, size/S

#2048 upgrade fluentbit-operator to v0.14.0
  roles/common/files/fluentbit-operator/init/fluentbit-operator-outputCustomResourceDefinition.yaml
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/L

#2055 fix applying prometheus crd metadata annotations tool long
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-0prometheusCustomResourceDefinition.yaml
  roles/ks-monitor/tasks/prometheus-operator.yaml
Labels: approved, lgtm, size/XXL

#2051 Add permission of ci/nodelabels
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, lgtm, size/XS

#2052 Fix the potential Jenkins panic issues
  deploy/cluster-configuration.yaml
  docs/vars.md
  roles/ks-devops/defaults/main.yaml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, lgtm, size/S
