Repository kubesphere/ks-installer, pull requests merged in 2022-10, with the labels that each got.

#2121 fix: redis-ha-configmap lost its formatting #2120
  roles/common/files/redis-ha/templates/_configs.tpl
Labels: approved, lgtm, size/XS

#2122 Delete clusterRoles
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/M

#2129 add opensearch dashboard
  deploy/cluster-configuration.yaml
  roles/common/files/elasticsearch/opensearch-dashboards-2.1.0.tgz
  roles/common/tasks/opensearch-install.yaml
  roles/common/templates/custom-values-opensearch-dashboard.yaml.j2
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/L

#2132 update record rules to support multicluster
  roles/ks-monitor/files/prometheus/etcd/prometheus-rulesEtcd.yaml
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheusRule.yaml
Labels: approved, lgtm, size/L

#2133 upgrade ks devops helm chart to 0.1.15
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.13.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.15.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/XS
