Repository kubesphere/ks-installer, pull requests merged in 2022-08, with the labels that each got.

#2046 Fix the wrong indent of tolerations in prometheus
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: approved, lgtm, size/XS

#2050 add support for switching the notfication language
  roles/ks-monitor/files/notification-manager/templates/zh-cn.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
  roles/ks-multicluster/files/kubefed/federatedcrds/notificationmanagers.notification.kubesphere.io.yaml
Labels: approved, lgtm, size/XXL

#2059 fix prometheus nodeSelector indent
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: approved, lgtm, size/XS

#2065 fix grafana configs
  roles/ks-monitor/files/prometheus/grafana/grafana-config.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-dashboardDefinitions.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-deployment.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheus.yaml
Labels: approved, lgtm, size/XXL

#2063 feat: support custom or random initial admin password
  deploy/cluster-configuration.yaml
  roles/check-result/tasks/main.yaml
  roles/check-result/templates/welcome.j2
  roles/ks-core/ks-core/files/ks-core/templates/_helpers.tpl
  roles/ks-core/ks-core/files/ks-core/templates/account.yaml
  roles/ks-core/ks-core/tasks/main.yaml
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
  roles/preinstall/tasks/precheck.yaml
Labels: approved, lgtm, size/M

#2061 upgrade kube-state-metrics version
  roles/download/defaults/main.yml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
Labels: approved, lgtm, size/S

#2070 Grant cluster list permission to authenticated users
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#2062 Delete the role-templates annotation for disabling role to users
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/S

#2075 Improve the Jenkins readiness setting
  deploy/cluster-configuration.yaml
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.10.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.13.tgz
  roles/ks-devops/tasks/main.yaml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, area/devops, lgtm, size/S

#2083 update openpitrix-job version to v3.3.1-rc.0
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#2082 Add roletemplates of CluseterRole for configration management
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/M

#2080 Fix the bug of wrong display name at frontend
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/S

#2089 cleanup: remove repeated judgment logic to create `istio-system` namespace
  roles/common/tasks/init-namespaces.yaml
Labels: approved, lgtm, size/XS

#2081 ks-installer integration with opensensearch
  controller/installRunner.py
  deploy/cluster-configuration.yaml
  roles/common/defaults/main.yaml
  roles/common/files/elasticsearch/opensearch-2.1.0.tgz
  roles/common/tasks/common-install.yaml
  roles/common/tasks/get_old_config.yaml
  roles/common/tasks/opensearch-install.yaml
  roles/common/templates/custom-values-opensearch-data.yaml.j2
  roles/common/templates/custom-values-opensearch-master.yaml.j2
  roles/download/defaults/main.yml
  roles/ks-auditing/tasks/fluentbit-operator.yaml
  roles/ks-auditing/templates/custom-output-opensearch-auditing.yaml.j2
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-events/tasks/fluentbit-operator.yaml
  roles/ks-events/templates/custom-output-opensearch-events.yaml.j2
  roles/ks-istio/tasks/jaeger-install.yaml
  roles/ks-istio/templates/jaeger-cr.yaml.j2
  roles/ks-logging/tasks/main.yaml
  roles/ks-logging/templates/custom-output-opensearch-logging.yaml.j2
Labels: approved, lgtm, size/XXL
