Repository kubesphere/ks-installer, pull requests merged in 2022-03, with the labels that each got.

#1901 Enable clustertemplates resources list and get for authenticated global role
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, area/devops, kind/feature, lgtm, size/XS

#1906 disable processes collector for node exporter
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-daemonset.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-serviceMonitor.yaml
  roles/ks-monitor/templates/node-exporter-daemonset.yaml.j2
Labels: lgtm, size/XS

#1910 Upgrade kube-events to the latest version
  roles/download/defaults/main.yml
  roles/ks-events/files/kube-events/Chart.yaml
  roles/ks-events/files/kube-events/crds/events.kubesphere.io_rulers.yaml
  roles/ks-events/files/kube-events/templates/crs/ruler.yaml
  roles/ks-events/files/kube-events/templates/operator/deploy.yaml
  roles/ks-events/files/kube-events/values.yaml
  roles/ks-events/tasks/main.yaml
Labels: lgtm, size/M

#1912 upgrade fluentbit-operator
  roles/common/files/fluentbit-operator/init/fluentbit-operator-filterCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-fluentbitCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-fluentbitconfigCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-inputCustomResourceDefinition.yaml
  roles/common/files/fluentbit-operator/init/fluentbit-operator-outputCustomResourceDefinition.yaml
  roles/download/defaults/main.yml
Labels: lgtm, size/XXL

#1909 Support custom node-export's port
  deploy/cluster-configuration.yaml
  roles/ks-monitor/templates/node-exporter-daemonset.yaml.j2
Labels: approved, lgtm, size/S

#1907 Set the role of the current cluster into the kubesphere-config configmap
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, lgtm, size/XS

#1918 refine edgeservices
  roles/edgeruntime/files/kubeedge/cloudcore/templates/deployment_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/deployment_edgeservice.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/service_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/values.yaml
  roles/edgeruntime/templates/custom-values-kubeedge.yaml.j2
Labels: lgtm, size/S

#1919 Refine edgeruntime version
  roles/edgeruntime/files/kubeedge/cloudcore/values.yaml
  roles/edgeruntime/templates/custom-values-kubeedge.yaml.j2
Labels: lgtm, size/S

#1921 Change KubeEdge version from 1.8.2 to 1.9.2 in all places
  roles/edgeruntime/files/kubeedge/cloudcore/Chart.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/README.md
  roles/edgeruntime/files/kubeedge/cloudcore/values.yaml
Labels: size/S
