Repository kubesphere/ks-installer, pull requests merged in 2022-09, with the labels that each got.

#2096 add opensearch curator
  roles/common/tasks/opensearch-install.yaml
  roles/common/templates/custom-values-opensearch-curator.yaml.j2
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/L

#2060 update notification manager helm chart to v2.1.0-rc.1
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/crds/bundle.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
Labels: approved, lgtm, size/XXL

#2094 Delete globalrole workspace-manager
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/L

#2095 Add GlobalRole platform-self-provisioner
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/M

#2108 integrate alerting v2beta1
  deploy/kubesphere-installer.yaml
  roles/ks-core/ks-core/files/ks-core/crds/alerting.kubesphere.io_clusterrulegroups.yaml
  roles/ks-core/ks-core/files/ks-core/crds/alerting.kubesphere.io_globalrulegroups.yaml
  roles/ks-core/ks-core/files/ks-core/crds/alerting.kubesphere.io_rulegroups.yaml
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/etcd/prometheus-alertRuleGroupsEtcd.yaml
  roles/ks-monitor/files/prometheus/etcd/prometheus-rulesEtcd.yaml
  roles/ks-monitor/files/prometheus/kube-prometheus/kube-prometheus-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kube-prometheus/kube-prometheus-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-thanosRuler.yaml
  roles/ks-monitor/templates/thanos-ruler-thanosRuler.yaml.j2
Labels: approved, lgtm, size/XXL

#2109 update prometheusrules and modify kube-state-metics metrics denylist.
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-prometheusRule.yaml
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
Labels: approved, lgtm, size/S

#2111 temporarily remove rules with last_over_time function
  roles/ks-monitor/files/prometheus/etcd/prometheus-alertRuleGroupsEtcd.yaml
Labels: approved, lgtm, size/S

#2113 add kubesphere component alerting
  roles/ks-monitor/files/prometheus/kubesphere/kubesphere-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kubesphere/kubesphere-serviceMonitorKsApiserver.yaml
  roles/ks-monitor/files/prometheus/kubesphere/kubesphere-serviceMonitorKsControllerManager.yaml
Labels: approved, lgtm, size/L

#2114 Fix:add module for displaying in frontend
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#2112 Disable manage-groups in custom role
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#2117 upgrade old globalrolebindings
  roles/ks-core/ks-core/tasks/main.yaml
Labels: approved, lgtm, size/XS

#2119 fix ks-core monitor not apply
  roles/ks-monitor/tasks/ks-core-monitor.yaml
  roles/ks-monitor/tasks/prometheus-stack.yaml
Labels: approved, lgtm, size/XS
