Repository kubesphere/ks-installer, pull requests merged in 2022-01, with the labels that each got.

#1888 enhance edgeruntime: sync upstream helm
  .gitignore
  deploy/cluster-configuration.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/README.md
  roles/edgeruntime/files/kubeedge/cloudcore/templates/configmap_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/daemonset_iptablesmanager.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/deployment_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/rbac_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/service_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/values.yaml
  roles/edgeruntime/templates/custom-values-kubeedge.yaml.j2
Labels: lgtm, size/L

#1872 upgrade ingress nginx version
  roles/download/defaults/main.yml
Labels: lgtm, size/XS

#1882 Upgrade Eleasticsearch helm chart to v6.8.22
  roles/common/templates/custom-values-elasticsearch.yaml.j2
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#1880 add terminal config
  deploy/cluster-configuration.yaml
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
Labels: approved, lgtm, size/S

#1889 Harbor 2.x images backup and restore
  scripts/harbor_images_backup.sh
  scripts/harbor_images_push.sh
Labels: approved, lgtm, size/M

#1869 Customizing the Istio installation configuration
  Dockerfile
  Dockerfile.complete
  Dockerfile.shelloperator
  deploy/cluster-configuration.yaml
  roles/ks-istio/tasks/main.yaml
  roles/ks-istio/templates/istio-custom-profile.yaml.j2
  roles/ks-istio/templates/istio-profile.yaml.j2
Labels: approved, lgtm, size/M

#1891 fix: add resource' request and limit to the jaeger-cr.
  roles/ks-istio/templates/jaeger-cr.yaml.j2
Labels: approved, lgtm, size/XS
