Repository kubesphere/ks-installer, pull requests merged in 2022-06, with the labels that each got.

#2009 fix: err format at gatekeeper webhook template
  roles/gatekeeper/files/gatekeeper/templates/gatekeeper-validating-webhook-configuration-validatingwebhookconfiguration.yaml
Labels: approved, lgtm, size/XS

#2015 update tools version
  Dockerfile
  Dockerfile.complete
  Dockerfile.shelloperator
Labels: approved, lgtm, size/S

#2007 create service account token
  roles/ks-core/ks-core/files/ks-core/templates/_helpers.tpl
  roles/ks-core/ks-core/files/ks-core/templates/serviceaccount.yaml
Labels: approved, lgtm, size/M

#2013 optimize ks-istio monitoring and reduce useless metrics
  roles/ks-istio/files/prometheus/prometheus-operator.yaml
Labels: approved, lgtm, size/XS

#2014 optimize ks-istio monitoring on release-3.2
  roles/ks-istio/files/prometheus/prometheus-operator.yaml
  roles/ks-monitor/files/prometheus/prometheus/additional-scrape-configs.yaml
Labels: approved, lgtm, size/XS

#2021 Adjust ks-istio-monitoring to ensure monitoring files are installed
  roles/ks-istio/files/prometheus/readme.md
  roles/ks-istio/tasks/main.yaml
  roles/ks-monitor/files/ks-istio-monitoring/prometheus-operator.yaml
  roles/ks-monitor/tasks/ks-istio-monitoring.yaml
  roles/ks-monitor/tasks/main.yaml
Labels: approved, lgtm, size/M

#2025 refine installation logic of redis
  roles/common/tasks/common-install.yaml
Labels: approved, lgtm, size/XS

#2023 upgrade default.yaml
  roles/download/defaults/main.yml
  roles/edgeruntime/templates/custom-values-kubeedge.yaml.j2
Labels: approved, lgtm, size/M

#2027 Support to read the repository path of argocd from the center file
  roles/download/defaults/main.yml
  roles/ks-devops/tasks/main.yaml
  roles/ks-devops/templates/argo-cd-values.yaml.j2
Labels: area/devops, lgtm, size/S

#2029 update Readme to v3.3.0
  README.md
  README_zh.md
  deploy/kubesphere-installer.yaml
  docs/IstioUpgradeGuide.md
  scripts/check_cluster_status.sh
Labels: approved, lgtm, size/M

#2030 refine upgrade command
  README.md
  README_zh.md
Labels: approved, lgtm, size/XS

#2036 Fix workspace management RBAC rules
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS
