Repository kubesphere/ks-installer, pull requests merged in 2022-02, with the labels that each got.

#1878 Update kubesphere-delete.sh
  scripts/kubesphere-delete.sh
Labels: approved, lgtm, size/XS

#1885 fix ks-installer lables bug
  README.md
  README_zh.md
  deploy/cluster-configuration.yaml
  deploy/kubesphere-installer.yaml
  docs/IstioUpgradeGuide.md
  scripts/check_cluster_status.sh
  scripts/kubesphere-delete.sh
Labels: approved, lgtm, size/M

#1897 Optimisation of container runtime selection for logging plugins
  deploy/cluster-configuration.yaml
  roles/common/tasks/fluentbit-install.yaml
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
  roles/ks-auditing/tasks/fluentbit-operator.yaml
  roles/ks-auditing/tasks/main.yaml
  roles/ks-auditing/templates/custom-filter-auditing.yaml.j2
  roles/ks-auditing/templates/custom-input-auditing.yaml.j2
  roles/ks-events/tasks/fluentbit-operator.yaml
  roles/ks-events/tasks/main.yaml
  roles/ks-events/templates/custom-filter-events.yaml.j2
  roles/ks-events/templates/custom-input-events.yaml.j2
  roles/ks-logging/tasks/main.yaml
  roles/ks-logging/templates/custom-input-logging.yaml.j2
  roles/ks-logging/templates/custom-input-systemd.yaml.j2
Labels: approved, lgtm, size/L
