Repository kubesphere/ks-installer, pull requests merged in 2023-06, with the labels that each got.

#2170 feat: upgrade ingress nginx version.
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#2173 feat: update ks-apiserver health check API
  roles/ks-core/ks-core/files/ks-core/templates/ks-apiserver.yml
Labels: approved, lgtm, size/XS

#2192 update prometheus stack
  roles/download/defaults/main.yml
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/alertmanager/alertmanager-secret.yaml
  roles/ks-monitor/files/prometheus/etcd/prometheus-alertRuleGroupsEtcd.yaml
  roles/ks-monitor/files/prometheus/grafana/grafana-dashboardDefinitions.yaml
  roles/ks-monitor/files/prometheus/kube-prometheus/kube-prometheus-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-clusterRole.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-service.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/kubesphere/kubesphere-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/prometheus-operator/prometheus-operator-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-clusterRole.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-clusterRoleBinding.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-podDisruptionBudget.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheus.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-roleBindingConfig.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-roleConfig.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-service.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceAccount.yaml
  roles/ks-monitor/files/prometheus/prometheus/prometheus-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-alertRuleGroups.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-podDisruptionBudget.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-prometheusRule.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-service.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-serviceMonitor.yaml
  roles/ks-monitor/files/prometheus/thanos-ruler/thanos-ruler-thanosRuler.yaml
  roles/ks-monitor/templates/thanos-ruler-thanosRuler.yaml.j2
Labels: approved, lgtm, size/XL

#2186 set --tls-cipher-suites option in metrics-server for CVE-2016-2183
  roles/metrics-server/files/metrics-server/metrics-server.yaml
  roles/metrics-server/templates/metrics-server.yaml.j2
Labels: approved, lgtm, size/XS

#2193 upgrade kubeedge
  roles/download/defaults/main.yml
  roles/edgeruntime/files/kubeedge/cloudcore/Chart.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/README.md
  roles/edgeruntime/files/kubeedge/cloudcore/crds/apps_v1alpha1_edgeapplication.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/crds/apps_v1alpha1_nodegroup.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/crds/cluster_objectsync_v1alpha1.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/crds/devices_v1alpha2_device.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/crds/devices_v1alpha2_devicemodel.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/crds/objectsync_v1alpha1.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/crds/operations_v1alpha1_nodeupgradejob.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/configmap_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/daemonset_iptablesmanager.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/deployment_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/deployment_controllermanager.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/deployment_edgeservice.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/rbac_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/rbac_controllermanager.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/templates/service_cloudcore.yaml
  roles/edgeruntime/files/kubeedge/cloudcore/values.yaml
  roles/edgeruntime/templates/custom-values-kubeedge.yaml.j2
Labels: approved, lgtm, size/XL

#2195 Adjusting the fluent-operator resource quota
  roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
Labels: approved, lgtm, size/XS

#2197 Bump OpenSearch and Dashboards to 2.6.0
  roles/common/files/elasticsearch/opensearch-2.1.0.tgz
  roles/common/files/elasticsearch/opensearch-2.6.0.tgz
  roles/common/files/elasticsearch/opensearch-dashboards-2.1.0.tgz
  roles/common/files/elasticsearch/opensearch-dashboards-2.6.0.tgz
  roles/common/tasks/opensearch-install.yaml
  roles/common/templates/custom-values-opensearch-data.yaml.j2
  roles/common/templates/custom-values-opensearch-master.yaml.j2
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/S

#2196 update ks-core helm chart version
  roles/ks-core/ks-core/files/ks-core/Chart.yaml
Labels: approved, lgtm, size/XS

#2199 Use OpenSearch to replace Elasticsearch
  controller/installRunner.py
  roles/common/files/elasticsearch/elasticsearch-1.22.1.tgz
  roles/common/tasks/common-install.yaml
  roles/common/tasks/es-install.yaml
  roles/common/templates/custom-values-elasticsearch.yaml.j2
Labels: approved, lgtm, size/L

#2201 modify elasticsearch file name && add elasticsearch curator
  roles/common/files/elasticsearch-curator/elasticsearch-curator-1.3.3.tgz
  roles/common/files/opensearch/opensearch-2.6.0.tgz
  roles/common/files/opensearch/opensearch-curator-1.3.3.tgz
  roles/common/files/opensearch/opensearch-dashboards-2.6.0.tgz
  roles/common/tasks/common-install.yaml
  roles/common/tasks/escurator-install.yaml
  roles/common/tasks/opensearch-install.yaml
  roles/common/templates/custom-values-opensearch-curator.yaml.j2
Labels: approved, lgtm, size/L

#2202 modify opensearch curator
  roles/common/files/opensearch/opensearch-curator-1.3.3.tgz
Labels: approved, lgtm, size/XS

#2204 migrate alert rules
  roles/ks-monitor/files/alert-migrate/migrate-alertrules.sh
  roles/ks-monitor/tasks/alert-migrate.yaml
  roles/ks-monitor/tasks/main.yaml
Labels: approved, lgtm, size/L

#2205 update prometheus stack
  roles/ks-monitor/files/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-serviceMonitorKubelet.yaml
  roles/ks-monitor/files/prometheus/node-exporter/node-exporter-serviceMonitor.yaml
  roles/ks-monitor/templates/kube-state-metrics-deployment.yaml.j2
  roles/ks-monitor/templates/prometheus-prometheus.yaml.j2
Labels: approved, lgtm, size/S
