Repository kubesphere/ks-installer, pull requests merged in 2023-07, with the labels that each got.

#2206 upgrade devops to 3.4.0
  controller/installRunner.py
  deploy/cluster-configuration.yaml
  playbooks/devops.yaml
  roles/download/defaults/main.yml
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
  roles/ks-devops/OWNERS
  roles/ks-devops/defaults/main.yaml
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.19.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.2.1.tgz
  roles/ks-devops/tasks/cd.yaml
  roles/ks-devops/tasks/ci.yaml
  roles/ks-devops/tasks/core.yaml
  roles/ks-devops/tasks/get_devops_config.yaml
  roles/ks-devops/tasks/main.yaml
  roles/ks-devops/templates/ks-devops-values.yaml.j2
Labels: approved, lgtm, size/XL

#2208 update notification manager helm chart to v2.3.0
  roles/download/defaults/main.yml
  roles/ks-monitor/files/notification-manager/Chart.yaml
  roles/ks-monitor/files/notification-manager/crds/bundle.yaml
  roles/ks-monitor/files/notification-manager/templates/hooks.yaml
  roles/ks-monitor/files/notification-manager/templates/notificationmanagers.yaml
  roles/ks-monitor/files/notification-manager/templates/template.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-monitor/templates/custom-values-notification.yaml.j2
Labels: approved, lgtm, size/XXL

#2210 update jenkins image tag to v3.4.0-2.319.3-1
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/XS

#2213 update Dockerfile
  Dockerfile.complete
  Dockerfile.shelloperator
Labels: approved, lgtm, size/XS

#2215 fix KubeStatefulSetReplicasMismatch rule summary
  roles/ks-monitor/files/prometheus/kubernetes/kubernetes-alertRuleGroups.yaml
Labels: approved, lgtm, size/XS

#2220 fix bug create notification channel failed
  roles/ks-monitor/files/notification-manager/templates/hooks.yaml
Labels: approved, lgtm, size/XS

#2217 Update tower leader election parameter config
  roles/ks-multicluster/templates/tower.yaml.j2
Labels: approved, lgtm, size/XS
