Repository kubesphere/ks-installer, pull requests merged in 2023-01, with the labels that each got.

#2150 delete role-template-manage-alerting-messages
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/M

#2154 upgrade logsidecar injector version to v1.2.0
  roles/download/defaults/main.yml
  roles/ks-logging/files/logsidecar-injector/Chart.yaml
  roles/ks-logging/tasks/logsidecar.yaml
Labels: approved, lgtm, size/S

#2156 fix dev_ tag parameter formatting failure
  deploy/cluster-configuration.yaml
Labels: approved, lgtm, size/XS

#2155 add -v argument
  scripts/offline-installation-tool.sh
Labels: approved, lgtm, size/XS

#2148 Change redis config for ks-apiserver HA
  roles/common/templates/redis.yaml.j2
  roles/ks-core/config/templates/kubesphere-config.yaml.j2
  roles/ks-core/ks-core/templates/custom-values-ks-core.yaml.j2
Labels: approved, lgtm, size/S

#2147 Fix: invalid aggregation role found: cluster-admin/cluster-viewer
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/S

#2136 [release-3.3] upgrade minio version to RELEASE.2022-11-08T05-27-07Z
  roles/common/files/minio-ha/Chart.yaml
  roles/common/files/minio-ha/README.md
  roles/common/files/minio-ha/values.yaml
  roles/common/tasks/minio-install.yaml
  roles/download/defaults/main.yml
Labels: approved, lgtm, size/S

#2131 Add an admission webhook for cluster crd
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
  roles/ks-core/ks-core/tasks/main.yaml
Labels: approved, kind/feature, lgtm, size/M

#2161 Upgrade task for role-template-alerting-management
  roles/ks-core/ks-core/tasks/main.yaml
Labels: approved, lgtm, size/S

#2166 update openpitrix-import-jobs version
  roles/download/defaults/main.yml
  roles/openpitrix/templates/ks-openpitrix-import.yaml.j2
Labels: approved, lgtm, size/XS

#2167 Revert "[master] [release-3.3] upgrade minio version to RELEASE.2022-11-08T05-27-07Z"
  roles/common/files/minio-ha/Chart.yaml
  roles/common/files/minio-ha/README.md
  roles/common/files/minio-ha/values.yaml
  roles/common/tasks/minio-install.yaml
  roles/download/defaults/main.yml
Labels: approved, size/S

#2169 Upgrade devops to 0.1.18
  deploy/cluster-configuration.yaml
  roles/download/defaults/main.yml
  roles/ks-devops/OWNERS
  roles/ks-devops/defaults/main.yaml
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.15.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.18.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/S

#2168 Upgrade devops to 0.1.18
  deploy/cluster-configuration.yaml
  roles/download/defaults/main.yml
  roles/ks-devops/OWNERS
  roles/ks-devops/defaults/main.yaml
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.15.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.1.18.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/S

#2171 Revert "[release-3.3] Add an admission webhook for cluster crd"
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
  roles/ks-core/ks-core/tasks/main.yaml
Labels: approved, size/M
