Repository kubesphere/ks-installer, pull requests merged in 2023-10, with the labels that each got.

#2236 update devops helm chart 0.2.1
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.2.1.tgz
Labels: approved, lgtm, size/XS

#2230 update readinessProbe/livenessProbe timeout of argocd servers
  roles/ks-devops/templates/argo-cd-values.yaml.j2
Labels: approved, lgtm, size/S

#2224 fix: add rule get-devops to create-devops role
  roles/ks-core/prepare/files/ks-init/role-templates.yaml
Labels: approved, lgtm, size/XS

#2232 Fix enabling logging failure after upgrading to v3.4.0 from v3.3.1
  controller/installRunner.py
Labels: approved, lgtm, size/S

#2226 fix: Gateway enable TCP/UPD traffic configuration prompt unknown field "tcp"
  roles/ks-core/ks-core/files/ks-core/crds/gateway.kubesphere.io_gateways.yaml
Labels: approved, lgtm, size/M

#2218 Update README_zh.md
  README_zh.md
Labels: approved, lgtm, size/XS

#2234 update storageclass-accessor webhook yaml
  roles/ks-core/ks-core/files/ks-core/templates/webhook.yaml
Labels: approved, lgtm, size/XS

#2245 waiting for CRD to complete the upgrade
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/XS

#2246 fix bug monitoring task failed when updating from v3.3.x to v3.4.0
  roles/ks-monitor/files/federated/federatednamespaces.yaml
  roles/ks-monitor/tasks/notification-manager.yaml
  roles/ks-multicluster/files/notification/kubesphere-monitoring-federated.yaml
  roles/ks-multicluster/files/notification/update_federated_crds.sh
  roles/ks-multicluster/tasks/main.yml
  roles/ks-multicluster/tasks/notification-manager.yaml
Labels: approved, lgtm, size/L

#2251 Fix the bug of too many spaces in an array
  roles/common/templates/custom-values-opensearch-data.yaml.j2
  roles/common/templates/custom-values-opensearch-master.yaml.j2
Labels: approved, lgtm, size/S

#2250 update devops helm-chart to 0.2.2
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.2.1.tgz
  roles/ks-devops/files/ks-devops/charts/ks-devops-0.2.2.tgz
  roles/ks-devops/tasks/main.yaml
Labels: approved, lgtm, size/XS
